/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [build/submodules/GLFW/include/GLFW/glfw3.h]
 */
#pragma warning disable 1591

namespace NiTiS.Native.GLFW;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GlfwJoystickHat
{
	Centered =  unchecked((int)0),
	Up =  unchecked((int)1),
	Right =  unchecked((int)2),
	Down =  unchecked((int)4),
	Left =  unchecked((int)8),
	RightUp =  unchecked((int)(Right | Up)),
	RightDown =  unchecked((int)(Right | Down)),
	LeftUp =  unchecked((int)(Left  | Up)),
	LeftDown =  unchecked((int)(Left  | Down)),
}

#pragma warning restore

