/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:18
 *  Source files: [build/submodules/GLFW/include/GLFW/glfw3.h]
 */
#pragma warning disable 1591

namespace NiTiS.Native.GLFW;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GlfwAction
{
	Release =  unchecked((int)0),
	Press =  unchecked((int)1),
	Repeat =  unchecked((int)2),
}

#pragma warning restore

