/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:18
 *  Source files: [build/submodules/GLFW/include/GLFW/glfw3.h]
 */
#pragma warning disable 1591

namespace NiTiS.Native.GLFW;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GlfwGamepadButton
{
	A =  unchecked((int)0),
	B =  unchecked((int)1),
	X =  unchecked((int)2),
	Y =  unchecked((int)3),
	LeftBumper =  unchecked((int)4),
	RightBumper =  unchecked((int)5),
	Back =  unchecked((int)6),
	Start =  unchecked((int)7),
	Guide =  unchecked((int)8),
	LeftThumb =  unchecked((int)9),
	RightThumb =  unchecked((int)10),
	DPadUp =  unchecked((int)11),
	DPadRight =  unchecked((int)12),
	DPadDown =  unchecked((int)13),
	DPadLeft =  unchecked((int)14),
	Last =  unchecked((int)DPadLeft),
	Cross =  unchecked((int)A),
	Circle =  unchecked((int)B),
	Square =  unchecked((int)X),
	Triangle =  unchecked((int)Y),
}

#pragma warning restore

