/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [build/submodules/GLFW/include/GLFW/glfw3.h]
 */
#pragma warning disable 1591

namespace NiTiS.Native.GLFW;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GlfwCursorForm
{
	Arrow =  unchecked((int)0x00036001),
	IBeam =  unchecked((int)0x00036002),
	Crosshair =  unchecked((int)0x00036003),
	PointingHand =  unchecked((int)0x00036004),
	ResizeEW =  unchecked((int)0x00036005),
	ResizeNS =  unchecked((int)0x00036006),
	ResizeNWSE =  unchecked((int)0x00036007),
	ResizeNESW =  unchecked((int)0x00036008),
	ResizeAll =  unchecked((int)0x00036009),
	NotAllowed =  unchecked((int)0x0003600A),
	HorizontalResize =  unchecked((int)ResizeEW),
	VerticalResize =  unchecked((int)ResizeNS),
	Hand =  unchecked((int)PointingHand),
}

#pragma warning restore

