/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [build/submodules/GLFW/include/GLFW/glfw3.h]
 */
#pragma warning disable 1591

namespace NiTiS.Native.GLFW;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GlfwJoystickId
{
	Joystick1 =  unchecked((int)0),
	Joystick2 =  unchecked((int)1),
	Joystick3 =  unchecked((int)2),
	Joystick4 =  unchecked((int)3),
	Joystick5 =  unchecked((int)4),
	Joystick6 =  unchecked((int)5),
	Joystick7 =  unchecked((int)6),
	Joystick8 =  unchecked((int)7),
	Joystick9 =  unchecked((int)8),
	Joystick10 =  unchecked((int)9),
	Joystick11 =  unchecked((int)10),
	Joystick12 =  unchecked((int)11),
	Joystick13 =  unchecked((int)12),
	Joystick14 =  unchecked((int)13),
	Joystick15 =  unchecked((int)14),
	Joystick16 =  unchecked((int)15),
	JoystickLast =  unchecked((int)Joystick16),
}

#pragma warning restore

