/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [build/submodules/GLFW/include/GLFW/glfw3.h]
 */
#pragma warning disable 1591

namespace NiTiS.Native.GLFW;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GlfwError
{
	NoError =  unchecked((int)0),
	NotInitialized =  unchecked((int)0x00010001),
	NoCurrentContext =  unchecked((int)0x00010002),
	InvalidEnum =  unchecked((int)0x00010003),
	InvalidValue =  unchecked((int)0x00010004),
	OutOfMemory =  unchecked((int)0x00010005),
	ApiUnavailable =  unchecked((int)0x00010006),
	VersionUnavailable =  unchecked((int)0x00010007),
	PlatformError =  unchecked((int)0x00010008),
	FormatUnavailable =  unchecked((int)0x00010009),
	NoWindowContext =  unchecked((int)0x0001000A),
	CursorUnavailable =  unchecked((int)0x0001000B),
	FeatureUnavailable =  unchecked((int)0x0001000C),
	FeatureUnimplemented =  unchecked((int)0x0001000D),
	PlatformUnavailable =  unchecked((int)0x0001000E),
}

#pragma warning restore

