/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [build/submodules/GLFW/include/GLFW/glfw3.h]
 */
#pragma warning disable 1591

namespace NiTiS.Native.GLFW;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GlfwGamepadAxis
{
	LeftX =  unchecked((int)0),
	LeftY =  unchecked((int)1),
	RightX =  unchecked((int)2),
	RightY =  unchecked((int)3),
	LeftTrigger =  unchecked((int)4),
	RightTrigger =  unchecked((int)5),
	Last =  unchecked((int)RightTrigger),
}

#pragma warning restore

