/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:18
 *  Source files: [build/submodules/GLFW/include/GLFW/glfw3.h]
 */
#pragma warning disable 1591

namespace NiTiS.Native.GLFW;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GlfwKeyMod
{
	Shift =  unchecked((int)0x0001),
	Control =  unchecked((int)0x0002),
	Alt =  unchecked((int)0x0004),
	Super =  unchecked((int)0x0008),
	CapsLock =  unchecked((int)0x0010),
	NumLock =  unchecked((int)0x0020),
}

#pragma warning restore

