/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [build/submodules/GLFW/include/GLFW/glfw3.h]
 */
#pragma warning disable 1591

namespace NiTiS.Native.GLFW;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GlfwMouseButton
{
	Button1 =  unchecked((int)0),
	Button2 =  unchecked((int)1),
	Button3 =  unchecked((int)2),
	Button4 =  unchecked((int)3),
	Button5 =  unchecked((int)4),
	Button6 =  unchecked((int)5),
	Button7 =  unchecked((int)6),
	Button8 =  unchecked((int)7),
	ButtonLast =  unchecked((int)Button8),
	ButtonLeft =  unchecked((int)Button1),
	ButtonRight =  unchecked((int)Button2),
	ButtonMiddle =  unchecked((int)Button3),
}

#pragma warning restore

