/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:18
 *  Source files: [build/submodules/GLFW/include/GLFW/glfw3.h]
 */
#pragma warning disable 1591

namespace NiTiS.Native.GLFW;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GlfwPlatform
{
	AnyPlatform =  unchecked((int)0x00060000),
	PlatformWin32 =  unchecked((int)0x00060001),
	PlatformCocoa =  unchecked((int)0x00060002),
	PlatformWayland =  unchecked((int)0x00060003),
	PlatformX11 =  unchecked((int)0x00060004),
	PlatformNull =  unchecked((int)0x00060005),
}

#pragma warning restore

