/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum AccumOp
{
	Accum =  unchecked((int)0x0100),
	Load =  unchecked((int)0x0101),
	Return =  unchecked((int)0x0102),
	Mult =  unchecked((int)0x0103),
	Add =  unchecked((int)0x0104),
}

#pragma warning restore

