/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ArrayObjectPNameATI
{
	ObjectBufferSizeAti =  unchecked((int)0x8764),
	ObjectBufferUsageAti =  unchecked((int)0x8765),
}

#pragma warning restore

