/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ArrayObjectUsageATI
{
	StaticAti =  unchecked((int)0x8760),
	DynamicAti =  unchecked((int)0x8761),
}

#pragma warning restore

