/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum AtomicCounterBufferPName
{
	AtomicCounterBufferReferencedByComputeShader =  unchecked((int)0x90ED),
	AtomicCounterBufferBinding =  unchecked((int)0x92C1),
	AtomicCounterBufferDataSize =  unchecked((int)0x92C4),
	AtomicCounterBufferActiveAtomicCounters =  unchecked((int)0x92C5),
	AtomicCounterBufferActiveAtomicCounterIndices =  unchecked((int)0x92C6),
	AtomicCounterBufferReferencedByVertexShader =  unchecked((int)0x92C7),
	AtomicCounterBufferReferencedByTessControlShader =  unchecked((int)0x92C8),
	AtomicCounterBufferReferencedByTessEvaluationShader =  unchecked((int)0x92C9),
	AtomicCounterBufferReferencedByGeometryShader =  unchecked((int)0x92CA),
	AtomicCounterBufferReferencedByFragmentShader =  unchecked((int)0x92CB),
}

#pragma warning restore

