/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum AttribMask
{
	CurrentBit =  unchecked((int)0x00000001),
	PointBit =  unchecked((int)0x00000002),
	LineBit =  unchecked((int)0x00000004),
	PolygonBit =  unchecked((int)0x00000008),
	PolygonStippleBit =  unchecked((int)0x00000010),
	PixelModeBit =  unchecked((int)0x00000020),
	LightingBit =  unchecked((int)0x00000040),
	FogBit =  unchecked((int)0x00000080),
	DepthBufferBit =  unchecked((int)0x00000100),
	AccumBufferBit =  unchecked((int)0x00000200),
	StencilBufferBit =  unchecked((int)0x00000400),
	ViewportBit =  unchecked((int)0x00000800),
	TransformBit =  unchecked((int)0x00001000),
	EnableBit =  unchecked((int)0x00002000),
	ColorBufferBit =  unchecked((int)0x00004000),
	HintBit =  unchecked((int)0x00008000),
	EvalBit =  unchecked((int)0x00010000),
	ListBit =  unchecked((int)0x00020000),
	TextureBit =  unchecked((int)0x00040000),
	ScissorBit =  unchecked((int)0x00080000),
	MultisampleBit =  unchecked((int)0x20000000),
	MultisampleBitArb =  unchecked((int)0x20000000),
	MultisampleBitExt =  unchecked((int)0x20000000),
	MultisampleBit3dfx =  unchecked((int)0x20000000),
	AllAttribBits =  unchecked((int)0xFFFFFFFF),
}

#pragma warning restore

