/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum BlendEquationModeEXT
{
	FuncAdd =  unchecked((int)0x8006),
	FuncAddExt =  unchecked((int)0x8006),
	Min =  unchecked((int)0x8007),
	MinExt =  unchecked((int)0x8007),
	Max =  unchecked((int)0x8008),
	MaxExt =  unchecked((int)0x8008),
	FuncSubtract =  unchecked((int)0x800A),
	FuncSubtractExt =  unchecked((int)0x800A),
	FuncReverseSubtract =  unchecked((int)0x800B),
	FuncReverseSubtractExt =  unchecked((int)0x800B),
	AlphaMinSgix =  unchecked((int)0x8320),
	AlphaMaxSgix =  unchecked((int)0x8321),
}

#pragma warning restore

