/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum BlendingFactor
{
	Zero =  unchecked((int)0),
	One =  unchecked((int)1),
	SrcColor =  unchecked((int)0x0300),
	OneMinusSrcColor =  unchecked((int)0x0301),
	SrcAlpha =  unchecked((int)0x0302),
	OneMinusSrcAlpha =  unchecked((int)0x0303),
	DstAlpha =  unchecked((int)0x0304),
	OneMinusDstAlpha =  unchecked((int)0x0305),
	DstColor =  unchecked((int)0x0306),
	OneMinusDstColor =  unchecked((int)0x0307),
	SrcAlphaSaturate =  unchecked((int)0x0308),
	ConstantColor =  unchecked((int)0x8001),
	OneMinusConstantColor =  unchecked((int)0x8002),
	ConstantAlpha =  unchecked((int)0x8003),
	OneMinusConstantAlpha =  unchecked((int)0x8004),
	Src1Alpha =  unchecked((int)0x8589),
	Src1Color =  unchecked((int)0x88F9),
	OneMinusSrc1Color =  unchecked((int)0x88FA),
	OneMinusSrc1Alpha =  unchecked((int)0x88FB),
}

#pragma warning restore

