/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum BlitFramebufferFilter
{
	Nearest =  unchecked((int)0x2600),
	Linear =  unchecked((int)0x2601),
}

#pragma warning restore

