/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum BufferUsageARB
{
	StreamDraw =  unchecked((int)0x88E0),
	StreamRead =  unchecked((int)0x88E1),
	StreamCopy =  unchecked((int)0x88E2),
	StaticDraw =  unchecked((int)0x88E4),
	StaticRead =  unchecked((int)0x88E5),
	StaticCopy =  unchecked((int)0x88E6),
	DynamicDraw =  unchecked((int)0x88E8),
	DynamicRead =  unchecked((int)0x88E9),
	DynamicCopy =  unchecked((int)0x88EA),
}

#pragma warning restore

