/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum BufferPNameARB
{
	BufferImmutableStorage =  unchecked((int)0x821F),
	BufferStorageFlags =  unchecked((int)0x8220),
	BufferSize =  unchecked((int)0x8764),
	BufferSizeArb =  unchecked((int)0x8764),
	BufferUsage =  unchecked((int)0x8765),
	BufferUsageArb =  unchecked((int)0x8765),
	BufferAccess =  unchecked((int)0x88BB),
	BufferAccessArb =  unchecked((int)0x88BB),
	BufferMapped =  unchecked((int)0x88BC),
	BufferMappedArb =  unchecked((int)0x88BC),
	BufferAccessFlags =  unchecked((int)0x911F),
	BufferMapLength =  unchecked((int)0x9120),
	BufferMapOffset =  unchecked((int)0x9121),
}

#pragma warning restore

