/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum BufferStorageMask
{
	DynamicStorageBit =  unchecked((int)0x0100),
	DynamicStorageBitExt =  unchecked((int)0x0100),
	ClientStorageBit =  unchecked((int)0x0200),
	ClientStorageBitExt =  unchecked((int)0x0200),
	SparseStorageBitArb =  unchecked((int)0x0400),
	LgpuSeparateStorageBitNvx =  unchecked((int)0x0800),
	PerGpuStorageBitNv =  unchecked((int)0x0800),
	ExternalStorageBitNvx =  unchecked((int)0x2000),
	MapReadBit =  unchecked((int)0x0001),
	MapReadBitExt =  unchecked((int)0x0001),
	MapWriteBit =  unchecked((int)0x0002),
	MapWriteBitExt =  unchecked((int)0x0002),
	MapPersistentBit =  unchecked((int)0x0040),
	MapPersistentBitExt =  unchecked((int)0x0040),
	MapCoherentBit =  unchecked((int)0x0080),
	MapCoherentBitExt =  unchecked((int)0x0080),
}

#pragma warning restore

