/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum BufferBitQCOM
{
	ColorBufferBit0Qcom =  unchecked((int)0x00000001),
	ColorBufferBit1Qcom =  unchecked((int)0x00000002),
	ColorBufferBit2Qcom =  unchecked((int)0x00000004),
	ColorBufferBit3Qcom =  unchecked((int)0x00000008),
	ColorBufferBit4Qcom =  unchecked((int)0x00000010),
	ColorBufferBit5Qcom =  unchecked((int)0x00000020),
	ColorBufferBit6Qcom =  unchecked((int)0x00000040),
	ColorBufferBit7Qcom =  unchecked((int)0x00000080),
	DepthBufferBit0Qcom =  unchecked((int)0x00000100),
	DepthBufferBit1Qcom =  unchecked((int)0x00000200),
	DepthBufferBit2Qcom =  unchecked((int)0x00000400),
	DepthBufferBit3Qcom =  unchecked((int)0x00000800),
	DepthBufferBit4Qcom =  unchecked((int)0x00001000),
	DepthBufferBit5Qcom =  unchecked((int)0x00002000),
	DepthBufferBit6Qcom =  unchecked((int)0x00004000),
	DepthBufferBit7Qcom =  unchecked((int)0x00008000),
	StencilBufferBit0Qcom =  unchecked((int)0x00010000),
	StencilBufferBit1Qcom =  unchecked((int)0x00020000),
	StencilBufferBit2Qcom =  unchecked((int)0x00040000),
	StencilBufferBit3Qcom =  unchecked((int)0x00080000),
	StencilBufferBit4Qcom =  unchecked((int)0x00100000),
	StencilBufferBit5Qcom =  unchecked((int)0x00200000),
	StencilBufferBit6Qcom =  unchecked((int)0x00400000),
	StencilBufferBit7Qcom =  unchecked((int)0x00800000),
	MultisampleBufferBit0Qcom =  unchecked((int)0x01000000),
	MultisampleBufferBit1Qcom =  unchecked((int)0x02000000),
	MultisampleBufferBit2Qcom =  unchecked((int)0x04000000),
	MultisampleBufferBit3Qcom =  unchecked((int)0x08000000),
	MultisampleBufferBit4Qcom =  unchecked((int)0x10000000),
	MultisampleBufferBit5Qcom =  unchecked((int)0x20000000),
	MultisampleBufferBit6Qcom =  unchecked((int)0x40000000),
	MultisampleBufferBit7Qcom =  unchecked((int)0x80000000),
}

#pragma warning restore

