/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum BufferAccessARB
{
	ReadOnly =  unchecked((int)0x88B8),
	WriteOnly =  unchecked((int)0x88B9),
	ReadWrite =  unchecked((int)0x88BA),
}

#pragma warning restore

