/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum Buffer
{
	Color =  unchecked((int)0x1800),
	Depth =  unchecked((int)0x1801),
	Stencil =  unchecked((int)0x1802),
}

#pragma warning restore

