/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ClampColorTargetARB
{
	ClampVertexColorArb =  unchecked((int)0x891A),
	ClampFragmentColorArb =  unchecked((int)0x891B),
	ClampReadColor =  unchecked((int)0x891C),
	ClampReadColorArb =  unchecked((int)0x891C),
}

#pragma warning restore

