/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ClampColorModeARB
{
	False =  unchecked((int)0),
	True =  unchecked((int)1),
	FixedOnly =  unchecked((int)0x891D),
	FixedOnlyArb =  unchecked((int)0x891D),
}

#pragma warning restore

