/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ClearBufferMask
{
	DepthBufferBit =  unchecked((int)0x00000100),
	AccumBufferBit =  unchecked((int)0x00000200),
	StencilBufferBit =  unchecked((int)0x00000400),
	ColorBufferBit =  unchecked((int)0x00004000),
	CoverageBufferBitNv =  unchecked((int)0x00008000),
}

#pragma warning restore

