/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ClientAttribMask
{
	ClientPixelStoreBit =  unchecked((int)0x00000001),
	ClientVertexArrayBit =  unchecked((int)0x00000002),
	ClientAllAttribBits =  unchecked((int)0xFFFFFFFF),
}

#pragma warning restore

