/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ClipPlaneName
{
	ClipPlane0 =  unchecked((int)0x3000),
	ClipDistance0 =  unchecked((int)0x3000),
	ClipPlane1 =  unchecked((int)0x3001),
	ClipDistance1 =  unchecked((int)0x3001),
	ClipPlane2 =  unchecked((int)0x3002),
	ClipDistance2 =  unchecked((int)0x3002),
	ClipPlane3 =  unchecked((int)0x3003),
	ClipDistance3 =  unchecked((int)0x3003),
	ClipPlane4 =  unchecked((int)0x3004),
	ClipDistance4 =  unchecked((int)0x3004),
	ClipPlane5 =  unchecked((int)0x3005),
	ClipDistance5 =  unchecked((int)0x3005),
	ClipDistance6 =  unchecked((int)0x3006),
	ClipDistance7 =  unchecked((int)0x3007),
}

#pragma warning restore

