/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ClipControlOrigin
{
	LowerLeft =  unchecked((int)0x8CA1),
	UpperLeft =  unchecked((int)0x8CA2),
}

#pragma warning restore

