/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ColorBuffer
{
	None =  unchecked((int)0),
	FrontLeft =  unchecked((int)0x0400),
	FrontRight =  unchecked((int)0x0401),
	BackLeft =  unchecked((int)0x0402),
	BackRight =  unchecked((int)0x0403),
	Front =  unchecked((int)0x0404),
	Back =  unchecked((int)0x0405),
	Left =  unchecked((int)0x0406),
	Right =  unchecked((int)0x0407),
	FrontAndBack =  unchecked((int)0x0408),
	ColorAttachment0 =  unchecked((int)0x8CE0),
	ColorAttachment1 =  unchecked((int)0x8CE1),
	ColorAttachment2 =  unchecked((int)0x8CE2),
	ColorAttachment3 =  unchecked((int)0x8CE3),
	ColorAttachment4 =  unchecked((int)0x8CE4),
	ColorAttachment5 =  unchecked((int)0x8CE5),
	ColorAttachment6 =  unchecked((int)0x8CE6),
	ColorAttachment7 =  unchecked((int)0x8CE7),
	ColorAttachment8 =  unchecked((int)0x8CE8),
	ColorAttachment9 =  unchecked((int)0x8CE9),
	ColorAttachment10 =  unchecked((int)0x8CEA),
	ColorAttachment11 =  unchecked((int)0x8CEB),
	ColorAttachment12 =  unchecked((int)0x8CEC),
	ColorAttachment13 =  unchecked((int)0x8CED),
	ColorAttachment14 =  unchecked((int)0x8CEE),
	ColorAttachment15 =  unchecked((int)0x8CEF),
	ColorAttachment16 =  unchecked((int)0x8CF0),
	ColorAttachment17 =  unchecked((int)0x8CF1),
	ColorAttachment18 =  unchecked((int)0x8CF2),
	ColorAttachment19 =  unchecked((int)0x8CF3),
	ColorAttachment20 =  unchecked((int)0x8CF4),
	ColorAttachment21 =  unchecked((int)0x8CF5),
	ColorAttachment22 =  unchecked((int)0x8CF6),
	ColorAttachment23 =  unchecked((int)0x8CF7),
	ColorAttachment24 =  unchecked((int)0x8CF8),
	ColorAttachment25 =  unchecked((int)0x8CF9),
	ColorAttachment26 =  unchecked((int)0x8CFA),
	ColorAttachment27 =  unchecked((int)0x8CFB),
	ColorAttachment28 =  unchecked((int)0x8CFC),
	ColorAttachment29 =  unchecked((int)0x8CFD),
	ColorAttachment30 =  unchecked((int)0x8CFE),
	ColorAttachment31 =  unchecked((int)0x8CFF),
}

#pragma warning restore

