/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ColorTableTarget
{
	ColorTable =  unchecked((int)0x80D0),
	PostConvolutionColorTable =  unchecked((int)0x80D1),
	PostColorMatrixColorTable =  unchecked((int)0x80D2),
	ProxyColorTable =  unchecked((int)0x80D3),
	ProxyPostConvolutionColorTable =  unchecked((int)0x80D4),
	ProxyPostColorMatrixColorTable =  unchecked((int)0x80D5),
}

#pragma warning restore

