/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ColorMaterialParameter
{
	Ambient =  unchecked((int)0x1200),
	Diffuse =  unchecked((int)0x1201),
	Specular =  unchecked((int)0x1202),
	Emission =  unchecked((int)0x1600),
	AmbientAndDiffuse =  unchecked((int)0x1602),
}

#pragma warning restore

