/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ColorTableTargetSGI
{
	TextureColorTableSgi =  unchecked((int)0x80BC),
	ProxyTextureColorTableSgi =  unchecked((int)0x80BD),
	ColorTable =  unchecked((int)0x80D0),
	ColorTableSgi =  unchecked((int)0x80D0),
	PostConvolutionColorTable =  unchecked((int)0x80D1),
	PostConvolutionColorTableSgi =  unchecked((int)0x80D1),
	PostColorMatrixColorTable =  unchecked((int)0x80D2),
	PostColorMatrixColorTableSgi =  unchecked((int)0x80D2),
	ProxyColorTable =  unchecked((int)0x80D3),
	ProxyColorTableSgi =  unchecked((int)0x80D3),
	ProxyPostConvolutionColorTable =  unchecked((int)0x80D4),
	ProxyPostConvolutionColorTableSgi =  unchecked((int)0x80D4),
	ProxyPostColorMatrixColorTable =  unchecked((int)0x80D5),
	ProxyPostColorMatrixColorTableSgi =  unchecked((int)0x80D5),
}

#pragma warning restore

