/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ColorTableParameterPName
{
	ColorTableScale =  unchecked((int)0x80D6),
	ColorTableScaleSgi =  unchecked((int)0x80D6),
	ColorTableBias =  unchecked((int)0x80D7),
	ColorTableBiasSgi =  unchecked((int)0x80D7),
	ColorTableFormat =  unchecked((int)0x80D8),
	ColorTableFormatSgi =  unchecked((int)0x80D8),
	ColorTableWidth =  unchecked((int)0x80D9),
	ColorTableWidthSgi =  unchecked((int)0x80D9),
	ColorTableRedSize =  unchecked((int)0x80DA),
	ColorTableRedSizeSgi =  unchecked((int)0x80DA),
	ColorTableGreenSize =  unchecked((int)0x80DB),
	ColorTableGreenSizeSgi =  unchecked((int)0x80DB),
	ColorTableBlueSize =  unchecked((int)0x80DC),
	ColorTableBlueSizeSgi =  unchecked((int)0x80DC),
	ColorTableAlphaSize =  unchecked((int)0x80DD),
	ColorTableAlphaSizeSgi =  unchecked((int)0x80DD),
	ColorTableLuminanceSize =  unchecked((int)0x80DE),
	ColorTableLuminanceSizeSgi =  unchecked((int)0x80DE),
	ColorTableIntensitySize =  unchecked((int)0x80DF),
	ColorTableIntensitySizeSgi =  unchecked((int)0x80DF),
}

#pragma warning restore

