/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum CombinerVariableNV
{
	VariableANv =  unchecked((int)0x8523),
	VariableBNv =  unchecked((int)0x8524),
	VariableCNv =  unchecked((int)0x8525),
	VariableDNv =  unchecked((int)0x8526),
	VariableENv =  unchecked((int)0x8527),
	VariableFNv =  unchecked((int)0x8528),
	VariableGNv =  unchecked((int)0x8529),
}

#pragma warning restore

