/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum CombinerRegisterNV
{
	Texture0Arb =  unchecked((int)0x84C0),
	Texture1Arb =  unchecked((int)0x84C1),
	PrimaryColorNv =  unchecked((int)0x852C),
	SecondaryColorNv =  unchecked((int)0x852D),
	Spare0Nv =  unchecked((int)0x852E),
	Spare1Nv =  unchecked((int)0x852F),
	DiscardNv =  unchecked((int)0x8530),
}

#pragma warning restore

