/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum CombinerScaleNV
{
	None =  unchecked((int)0),
	ScaleByTwoNv =  unchecked((int)0x853E),
	ScaleByFourNv =  unchecked((int)0x853F),
	ScaleByOneHalfNv =  unchecked((int)0x8540),
}

#pragma warning restore

