/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum CombinerStageNV
{
	Combiner0Nv =  unchecked((int)0x8550),
	Combiner1Nv =  unchecked((int)0x8551),
	Combiner2Nv =  unchecked((int)0x8552),
	Combiner3Nv =  unchecked((int)0x8553),
	Combiner4Nv =  unchecked((int)0x8554),
	Combiner5Nv =  unchecked((int)0x8555),
	Combiner6Nv =  unchecked((int)0x8556),
	Combiner7Nv =  unchecked((int)0x8557),
}

#pragma warning restore

