/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum CombinerMappingNV
{
	UnsignedIdentityNv =  unchecked((int)0x8536),
	UnsignedInvertNv =  unchecked((int)0x8537),
	ExpandNormalNv =  unchecked((int)0x8538),
	ExpandNegateNv =  unchecked((int)0x8539),
	HalfBiasNormalNv =  unchecked((int)0x853A),
	HalfBiasNegateNv =  unchecked((int)0x853B),
	SignedIdentityNv =  unchecked((int)0x853C),
	SignedNegateNv =  unchecked((int)0x853D),
}

#pragma warning restore

