/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum CommandOpcodesNV
{
	TerminateSequenceCommandNv =  unchecked((int)0x0000),
	NopCommandNv =  unchecked((int)0x0001),
	DrawElementsCommandNv =  unchecked((int)0x0002),
	DrawArraysCommandNv =  unchecked((int)0x0003),
	DrawElementsStripCommandNv =  unchecked((int)0x0004),
	DrawArraysStripCommandNv =  unchecked((int)0x0005),
	DrawElementsInstancedCommandNv =  unchecked((int)0x0006),
	DrawArraysInstancedCommandNv =  unchecked((int)0x0007),
	ElementAddressCommandNv =  unchecked((int)0x0008),
	AttributeAddressCommandNv =  unchecked((int)0x0009),
	UniformAddressCommandNv =  unchecked((int)0x000A),
	BlendColorCommandNv =  unchecked((int)0x000B),
	StencilRefCommandNv =  unchecked((int)0x000C),
	LineWidthCommandNv =  unchecked((int)0x000D),
	PolygonOffsetCommandNv =  unchecked((int)0x000E),
	AlphaRefCommandNv =  unchecked((int)0x000F),
	ViewportCommandNv =  unchecked((int)0x0010),
	ScissorCommandNv =  unchecked((int)0x0011),
	FrontFaceCommandNv =  unchecked((int)0x0012),
}

#pragma warning restore

