/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ConditionalRenderMode
{
	QueryWait =  unchecked((int)0x8E13),
	QueryNoWait =  unchecked((int)0x8E14),
	QueryByRegionWait =  unchecked((int)0x8E15),
	QueryByRegionNoWait =  unchecked((int)0x8E16),
	QueryWaitInverted =  unchecked((int)0x8E17),
	QueryNoWaitInverted =  unchecked((int)0x8E18),
	QueryByRegionWaitInverted =  unchecked((int)0x8E19),
	QueryByRegionNoWaitInverted =  unchecked((int)0x8E1A),
}

#pragma warning restore

