/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ConvolutionTargetEXT
{
	Convolution1d =  unchecked((int)0x8010),
	Convolution1dExt =  unchecked((int)0x8010),
	Convolution2d =  unchecked((int)0x8011),
	Convolution2dExt =  unchecked((int)0x8011),
}

#pragma warning restore

