/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ConvolutionParameter
{
	ConvolutionBorderMode =  unchecked((int)0x8013),
	ConvolutionBorderModeExt =  unchecked((int)0x8013),
	ConvolutionFilterScale =  unchecked((int)0x8014),
	ConvolutionFilterScaleExt =  unchecked((int)0x8014),
	ConvolutionFilterBias =  unchecked((int)0x8015),
	ConvolutionFilterBiasExt =  unchecked((int)0x8015),
	ConvolutionFormat =  unchecked((int)0x8017),
	ConvolutionFormatExt =  unchecked((int)0x8017),
	ConvolutionWidth =  unchecked((int)0x8018),
	ConvolutionWidthExt =  unchecked((int)0x8018),
	ConvolutionHeight =  unchecked((int)0x8019),
	ConvolutionHeightExt =  unchecked((int)0x8019),
	MaxConvolutionWidth =  unchecked((int)0x801A),
	MaxConvolutionWidthExt =  unchecked((int)0x801A),
	MaxConvolutionHeight =  unchecked((int)0x801B),
	MaxConvolutionHeightExt =  unchecked((int)0x801B),
	ConvolutionBorderColor =  unchecked((int)0x8154),
}

#pragma warning restore

