/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum CopyImageSubDataTarget
{
	Texture1d =  unchecked((int)0x0DE0),
	Texture2d =  unchecked((int)0x0DE1),
	Texture3d =  unchecked((int)0x806F),
	TextureRectangle =  unchecked((int)0x84F5),
	TextureCubeMap =  unchecked((int)0x8513),
	Texture1dArray =  unchecked((int)0x8C18),
	Texture2dArray =  unchecked((int)0x8C1A),
	Renderbuffer =  unchecked((int)0x8D41),
	TextureCubeMapArray =  unchecked((int)0x9009),
	Texture2dMultisample =  unchecked((int)0x9100),
	Texture2dMultisampleArray =  unchecked((int)0x9102),
}

#pragma warning restore

