/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum CopyBufferSubDataTarget
{
	ArrayBuffer =  unchecked((int)0x8892),
	ElementArrayBuffer =  unchecked((int)0x8893),
	PixelPackBuffer =  unchecked((int)0x88EB),
	PixelUnpackBuffer =  unchecked((int)0x88EC),
	UniformBuffer =  unchecked((int)0x8A11),
	TextureBuffer =  unchecked((int)0x8C2A),
	TransformFeedbackBuffer =  unchecked((int)0x8C8E),
	CopyReadBuffer =  unchecked((int)0x8F36),
	CopyWriteBuffer =  unchecked((int)0x8F37),
	DrawIndirectBuffer =  unchecked((int)0x8F3F),
	ShaderStorageBuffer =  unchecked((int)0x90D2),
	DispatchIndirectBuffer =  unchecked((int)0x90EE),
	QueryBuffer =  unchecked((int)0x9192),
	AtomicCounterBuffer =  unchecked((int)0x92C0),
}

#pragma warning restore

