/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum CullParameterEXT
{
	CullVertexEyePositionExt =  unchecked((int)0x81AB),
	CullVertexObjectPositionExt =  unchecked((int)0x81AC),
}

#pragma warning restore

