/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum DataTypeEXT
{
	ScalarExt =  unchecked((int)0x87BE),
	VectorExt =  unchecked((int)0x87BF),
	MatrixExt =  unchecked((int)0x87C0),
}

#pragma warning restore

