/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum DebugSource
{
	DontCare =  unchecked((int)0x1100),
	DebugSourceApi =  unchecked((int)0x8246),
	DebugSourceWindowSystem =  unchecked((int)0x8247),
	DebugSourceShaderCompiler =  unchecked((int)0x8248),
	DebugSourceThirdParty =  unchecked((int)0x8249),
	DebugSourceApplication =  unchecked((int)0x824A),
	DebugSourceOther =  unchecked((int)0x824B),
}

#pragma warning restore

