/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum DebugType
{
	DontCare =  unchecked((int)0x1100),
	DebugTypeError =  unchecked((int)0x824C),
	DebugTypeDeprecatedBehavior =  unchecked((int)0x824D),
	DebugTypeUndefinedBehavior =  unchecked((int)0x824E),
	DebugTypePortability =  unchecked((int)0x824F),
	DebugTypePerformance =  unchecked((int)0x8250),
	DebugTypeOther =  unchecked((int)0x8251),
	DebugTypeMarker =  unchecked((int)0x8268),
	DebugTypePushGroup =  unchecked((int)0x8269),
	DebugTypePopGroup =  unchecked((int)0x826A),
}

#pragma warning restore

