/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum DebugSeverity
{
	DontCare =  unchecked((int)0x1100),
	DebugSeverityNotification =  unchecked((int)0x826B),
	DebugSeverityHigh =  unchecked((int)0x9146),
	DebugSeverityMedium =  unchecked((int)0x9147),
	DebugSeverityLow =  unchecked((int)0x9148),
}

#pragma warning restore

