/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum DepthStencilTextureMode
{
	StencilIndex =  unchecked((int)0x1901),
	DepthComponent =  unchecked((int)0x1902),
}

#pragma warning restore

