/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ErrorCode
{
	NoError =  unchecked((int)0),
	InvalidEnum =  unchecked((int)0x0500),
	InvalidValue =  unchecked((int)0x0501),
	InvalidOperation =  unchecked((int)0x0502),
	StackOverflow =  unchecked((int)0x0503),
	StackUnderflow =  unchecked((int)0x0504),
	OutOfMemory =  unchecked((int)0x0505),
	InvalidFramebufferOperation =  unchecked((int)0x0506),
	InvalidFramebufferOperationExt =  unchecked((int)0x0506),
	InvalidFramebufferOperationOes =  unchecked((int)0x0506),
	TableTooLargeExt =  unchecked((int)0x8031),
	TableTooLarge =  unchecked((int)0x8031),
	TextureTooLargeExt =  unchecked((int)0x8065),
}

#pragma warning restore

