/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum EvalTargetNV
{
	Eval2dNv =  unchecked((int)0x86C0),
	EvalTriangular2dNv =  unchecked((int)0x86C1),
}

#pragma warning restore

