/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ExternalHandleType
{
	HandleTypeOpaqueFdExt =  unchecked((int)0x9586),
	HandleTypeOpaqueWin32Ext =  unchecked((int)0x9587),
	HandleTypeOpaqueWin32KmtExt =  unchecked((int)0x9588),
	HandleTypeD3d12TilepoolExt =  unchecked((int)0x9589),
	HandleTypeD3d12ResourceExt =  unchecked((int)0x958A),
	HandleTypeD3d11ImageExt =  unchecked((int)0x958B),
	HandleTypeD3d11ImageKmtExt =  unchecked((int)0x958C),
	HandleTypeD3d12FenceExt =  unchecked((int)0x9594),
}

#pragma warning restore

