/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FeedbackType
{
	_2d =  unchecked((int)0x0600),
	_3d =  unchecked((int)0x0601),
	_3dColor =  unchecked((int)0x0602),
	_3dColorTexture =  unchecked((int)0x0603),
	_4dColorTexture =  unchecked((int)0x0604),
}

#pragma warning restore

