/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FeedbackType
{
	2d =  unchecked((int)0x0600),
	3d =  unchecked((int)0x0601),
	3dColor =  unchecked((int)0x0602),
	3dColorTexture =  unchecked((int)0x0603),
	4dColorTexture =  unchecked((int)0x0604),
}

#pragma warning restore

