/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FeedBackToken
{
	PassThroughToken =  unchecked((int)0x0700),
	PointToken =  unchecked((int)0x0701),
	LineToken =  unchecked((int)0x0702),
	PolygonToken =  unchecked((int)0x0703),
	BitmapToken =  unchecked((int)0x0704),
	DrawPixelToken =  unchecked((int)0x0705),
	CopyPixelToken =  unchecked((int)0x0706),
	LineResetToken =  unchecked((int)0x0707),
}

#pragma warning restore

