/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FfdTargetSGIX
{
	GeometryDeformationSgix =  unchecked((int)0x8194),
	TextureDeformationSgix =  unchecked((int)0x8195),
}

#pragma warning restore

