/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FogMode
{
	Exp =  unchecked((int)0x0800),
	Exp2 =  unchecked((int)0x0801),
	Linear =  unchecked((int)0x2601),
	FogFuncSgis =  unchecked((int)0x812A),
}

#pragma warning restore

