/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FogPName
{
	FogIndex =  unchecked((int)0x0B61),
	FogDensity =  unchecked((int)0x0B62),
	FogStart =  unchecked((int)0x0B63),
	FogEnd =  unchecked((int)0x0B64),
	FogMode =  unchecked((int)0x0B65),
	FogCoordSrc =  unchecked((int)0x8450),
}

#pragma warning restore

