/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FogParameter
{
	FogIndex =  unchecked((int)0x0B61),
	FogDensity =  unchecked((int)0x0B62),
	FogStart =  unchecked((int)0x0B63),
	FogEnd =  unchecked((int)0x0B64),
	FogMode =  unchecked((int)0x0B65),
	FogColor =  unchecked((int)0x0B66),
	FogOffsetValueSgix =  unchecked((int)0x8199),
}

#pragma warning restore

