/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FoveationConfigBitQCOM
{
	FoveationEnableBitQcom =  unchecked((int)0x00000001),
	FoveationScaledBinMethodBitQcom =  unchecked((int)0x00000002),
	FoveationSubsampledLayoutMethodBitQcom =  unchecked((int)0x00000004),
}

#pragma warning restore

