/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FragmentLightNameSGIX
{
	FragmentLight0Sgix =  unchecked((int)0x840C),
	FragmentLight1Sgix =  unchecked((int)0x840D),
	FragmentLight2Sgix =  unchecked((int)0x840E),
	FragmentLight3Sgix =  unchecked((int)0x840F),
	FragmentLight4Sgix =  unchecked((int)0x8410),
	FragmentLight5Sgix =  unchecked((int)0x8411),
	FragmentLight6Sgix =  unchecked((int)0x8412),
	FragmentLight7Sgix =  unchecked((int)0x8413),
}

#pragma warning restore

