/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FragmentShaderConATI
{
	Con0Ati =  unchecked((int)0x8941),
	Con1Ati =  unchecked((int)0x8942),
	Con2Ati =  unchecked((int)0x8943),
	Con3Ati =  unchecked((int)0x8944),
	Con4Ati =  unchecked((int)0x8945),
	Con5Ati =  unchecked((int)0x8946),
	Con6Ati =  unchecked((int)0x8947),
	Con7Ati =  unchecked((int)0x8948),
	Con8Ati =  unchecked((int)0x8949),
	Con9Ati =  unchecked((int)0x894A),
	Con10Ati =  unchecked((int)0x894B),
	Con11Ati =  unchecked((int)0x894C),
	Con12Ati =  unchecked((int)0x894D),
	Con13Ati =  unchecked((int)0x894E),
	Con14Ati =  unchecked((int)0x894F),
	Con15Ati =  unchecked((int)0x8950),
	Con16Ati =  unchecked((int)0x8951),
	Con17Ati =  unchecked((int)0x8952),
	Con18Ati =  unchecked((int)0x8953),
	Con19Ati =  unchecked((int)0x8954),
	Con20Ati =  unchecked((int)0x8955),
	Con21Ati =  unchecked((int)0x8956),
	Con22Ati =  unchecked((int)0x8957),
	Con23Ati =  unchecked((int)0x8958),
	Con24Ati =  unchecked((int)0x8959),
	Con25Ati =  unchecked((int)0x895A),
	Con26Ati =  unchecked((int)0x895B),
	Con27Ati =  unchecked((int)0x895C),
	Con28Ati =  unchecked((int)0x895D),
	Con29Ati =  unchecked((int)0x895E),
	Con30Ati =  unchecked((int)0x895F),
	Con31Ati =  unchecked((int)0x8960),
}

#pragma warning restore

