/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FragmentShaderDestModMaskATI
{
	2xBitAti =  unchecked((int)0x00000001),
	4xBitAti =  unchecked((int)0x00000002),
	8xBitAti =  unchecked((int)0x00000004),
	HalfBitAti =  unchecked((int)0x00000008),
	QuarterBitAti =  unchecked((int)0x00000010),
	EighthBitAti =  unchecked((int)0x00000020),
	SaturateBitAti =  unchecked((int)0x00000040),
	None =  unchecked((int)0),
}

#pragma warning restore

