/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FragmentOp3ATI
{
	MadAti =  unchecked((int)0x8968),
	LerpAti =  unchecked((int)0x8969),
	CndAti =  unchecked((int)0x896A),
	Cnd0Ati =  unchecked((int)0x896B),
	Dot2AddAti =  unchecked((int)0x896C),
}

#pragma warning restore

