/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FragmentLightParameterSGIX
{
	Ambient =  unchecked((int)0x1200),
	Diffuse =  unchecked((int)0x1201),
	Specular =  unchecked((int)0x1202),
	Position =  unchecked((int)0x1203),
	SpotDirection =  unchecked((int)0x1204),
	SpotExponent =  unchecked((int)0x1205),
	SpotCutoff =  unchecked((int)0x1206),
	ConstantAttenuation =  unchecked((int)0x1207),
	LinearAttenuation =  unchecked((int)0x1208),
	QuadraticAttenuation =  unchecked((int)0x1209),
}

#pragma warning restore

