/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FragmentShaderRegATI
{
	Reg0Ati =  unchecked((int)0x8921),
	Reg1Ati =  unchecked((int)0x8922),
	Reg2Ati =  unchecked((int)0x8923),
	Reg3Ati =  unchecked((int)0x8924),
	Reg4Ati =  unchecked((int)0x8925),
	Reg5Ati =  unchecked((int)0x8926),
	Reg6Ati =  unchecked((int)0x8927),
	Reg7Ati =  unchecked((int)0x8928),
	Reg8Ati =  unchecked((int)0x8929),
	Reg9Ati =  unchecked((int)0x892A),
	Reg10Ati =  unchecked((int)0x892B),
	Reg11Ati =  unchecked((int)0x892C),
	Reg12Ati =  unchecked((int)0x892D),
	Reg13Ati =  unchecked((int)0x892E),
	Reg14Ati =  unchecked((int)0x892F),
	Reg15Ati =  unchecked((int)0x8930),
	Reg16Ati =  unchecked((int)0x8931),
	Reg17Ati =  unchecked((int)0x8932),
	Reg18Ati =  unchecked((int)0x8933),
	Reg19Ati =  unchecked((int)0x8934),
	Reg20Ati =  unchecked((int)0x8935),
	Reg21Ati =  unchecked((int)0x8936),
	Reg22Ati =  unchecked((int)0x8937),
	Reg23Ati =  unchecked((int)0x8938),
	Reg24Ati =  unchecked((int)0x8939),
	Reg25Ati =  unchecked((int)0x893A),
	Reg26Ati =  unchecked((int)0x893B),
	Reg27Ati =  unchecked((int)0x893C),
	Reg28Ati =  unchecked((int)0x893D),
	Reg29Ati =  unchecked((int)0x893E),
	Reg30Ati =  unchecked((int)0x893F),
	Reg31Ati =  unchecked((int)0x8940),
}

#pragma warning restore

