/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FragmentLightModelParameterSGIX
{
	FragmentLightModelLocalViewerSgix =  unchecked((int)0x8408),
	FragmentLightModelTwoSideSgix =  unchecked((int)0x8409),
	FragmentLightModelAmbientSgix =  unchecked((int)0x840A),
	FragmentLightModelNormalInterpolationSgix =  unchecked((int)0x840B),
}

#pragma warning restore

