/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FramebufferStatus
{
	FramebufferUndefined =  unchecked((int)0x8219),
	FramebufferComplete =  unchecked((int)0x8CD5),
	FramebufferIncompleteAttachment =  unchecked((int)0x8CD6),
	FramebufferIncompleteMissingAttachment =  unchecked((int)0x8CD7),
	FramebufferIncompleteDrawBuffer =  unchecked((int)0x8CDB),
	FramebufferIncompleteReadBuffer =  unchecked((int)0x8CDC),
	FramebufferUnsupported =  unchecked((int)0x8CDD),
	FramebufferIncompleteMultisample =  unchecked((int)0x8D56),
	FramebufferIncompleteLayerTargets =  unchecked((int)0x8DA8),
}

#pragma warning restore

