/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FramebufferTarget
{
	ReadFramebuffer =  unchecked((int)0x8CA8),
	DrawFramebuffer =  unchecked((int)0x8CA9),
	Framebuffer =  unchecked((int)0x8D40),
	FramebufferOes =  unchecked((int)0x8D40),
}

#pragma warning restore

