/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FramebufferParameterName
{
	FramebufferDefaultWidth =  unchecked((int)0x9310),
	FramebufferDefaultHeight =  unchecked((int)0x9311),
	FramebufferDefaultLayers =  unchecked((int)0x9312),
	FramebufferDefaultSamples =  unchecked((int)0x9313),
	FramebufferDefaultFixedSampleLocations =  unchecked((int)0x9314),
}

#pragma warning restore

