/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FramebufferAttachmentParameterName
{
	FramebufferAttachmentColorEncoding =  unchecked((int)0x8210),
	FramebufferAttachmentColorEncodingExt =  unchecked((int)0x8210),
	FramebufferAttachmentComponentType =  unchecked((int)0x8211),
	FramebufferAttachmentComponentTypeExt =  unchecked((int)0x8211),
	FramebufferAttachmentRedSize =  unchecked((int)0x8212),
	FramebufferAttachmentGreenSize =  unchecked((int)0x8213),
	FramebufferAttachmentBlueSize =  unchecked((int)0x8214),
	FramebufferAttachmentAlphaSize =  unchecked((int)0x8215),
	FramebufferAttachmentDepthSize =  unchecked((int)0x8216),
	FramebufferAttachmentStencilSize =  unchecked((int)0x8217),
	FramebufferAttachmentObjectType =  unchecked((int)0x8CD0),
	FramebufferAttachmentObjectTypeExt =  unchecked((int)0x8CD0),
	FramebufferAttachmentObjectTypeOes =  unchecked((int)0x8CD0),
	FramebufferAttachmentObjectName =  unchecked((int)0x8CD1),
	FramebufferAttachmentObjectNameExt =  unchecked((int)0x8CD1),
	FramebufferAttachmentObjectNameOes =  unchecked((int)0x8CD1),
	FramebufferAttachmentTextureLevel =  unchecked((int)0x8CD2),
	FramebufferAttachmentTextureLevelExt =  unchecked((int)0x8CD2),
	FramebufferAttachmentTextureLevelOes =  unchecked((int)0x8CD2),
	FramebufferAttachmentTextureCubeMapFace =  unchecked((int)0x8CD3),
	FramebufferAttachmentTextureCubeMapFaceExt =  unchecked((int)0x8CD3),
	FramebufferAttachmentTextureCubeMapFaceOes =  unchecked((int)0x8CD3),
	FramebufferAttachmentTexture3dZoffsetExt =  unchecked((int)0x8CD4),
	FramebufferAttachmentTexture3dZoffsetOes =  unchecked((int)0x8CD4),
	FramebufferAttachmentTextureLayer =  unchecked((int)0x8CD4),
	FramebufferAttachmentTextureLayerExt =  unchecked((int)0x8CD4),
	FramebufferAttachmentTextureSamplesExt =  unchecked((int)0x8D6C),
	FramebufferAttachmentLayered =  unchecked((int)0x8DA7),
	FramebufferAttachmentLayeredArb =  unchecked((int)0x8DA7),
	FramebufferAttachmentLayeredExt =  unchecked((int)0x8DA7),
	FramebufferAttachmentLayeredOes =  unchecked((int)0x8DA7),
	FramebufferAttachmentTextureScaleImg =  unchecked((int)0x913F),
	FramebufferAttachmentTextureNumViewsOvr =  unchecked((int)0x9630),
	FramebufferAttachmentTextureBaseViewIndexOvr =  unchecked((int)0x9632),
}

#pragma warning restore

