/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum FrontFaceDirection
{
	Cw =  unchecked((int)0x0900),
	Ccw =  unchecked((int)0x0901),
}

#pragma warning restore

