/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GetFramebufferParameter
{
	Doublebuffer =  unchecked((int)0x0C32),
	Stereo =  unchecked((int)0x0C33),
	SampleBuffers =  unchecked((int)0x80A8),
	Samples =  unchecked((int)0x80A9),
	ImplementationColorReadType =  unchecked((int)0x8B9A),
	ImplementationColorReadFormat =  unchecked((int)0x8B9B),
	FramebufferDefaultWidth =  unchecked((int)0x9310),
	FramebufferDefaultHeight =  unchecked((int)0x9311),
	FramebufferDefaultLayers =  unchecked((int)0x9312),
	FramebufferDefaultSamples =  unchecked((int)0x9313),
	FramebufferDefaultFixedSampleLocations =  unchecked((int)0x9314),
}

#pragma warning restore

