/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GetHistogramParameterPNameEXT
{
	HistogramWidth =  unchecked((int)0x8026),
	HistogramWidthExt =  unchecked((int)0x8026),
	HistogramFormat =  unchecked((int)0x8027),
	HistogramFormatExt =  unchecked((int)0x8027),
	HistogramRedSize =  unchecked((int)0x8028),
	HistogramRedSizeExt =  unchecked((int)0x8028),
	HistogramGreenSize =  unchecked((int)0x8029),
	HistogramGreenSizeExt =  unchecked((int)0x8029),
	HistogramBlueSize =  unchecked((int)0x802A),
	HistogramBlueSizeExt =  unchecked((int)0x802A),
	HistogramAlphaSize =  unchecked((int)0x802B),
	HistogramAlphaSizeExt =  unchecked((int)0x802B),
	HistogramLuminanceSize =  unchecked((int)0x802C),
	HistogramLuminanceSizeExt =  unchecked((int)0x802C),
	HistogramSink =  unchecked((int)0x802D),
	HistogramSinkExt =  unchecked((int)0x802D),
}

#pragma warning restore

