/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GetMinmaxParameterPNameEXT
{
	MinmaxFormat =  unchecked((int)0x802F),
	MinmaxFormatExt =  unchecked((int)0x802F),
	MinmaxSink =  unchecked((int)0x8030),
	MinmaxSinkExt =  unchecked((int)0x8030),
}

#pragma warning restore

