/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GetPointervPName
{
	FeedbackBufferPointer =  unchecked((int)0x0DF0),
	SelectionBufferPointer =  unchecked((int)0x0DF3),
	VertexArrayPointer =  unchecked((int)0x808E),
	VertexArrayPointerExt =  unchecked((int)0x808E),
	NormalArrayPointer =  unchecked((int)0x808F),
	NormalArrayPointerExt =  unchecked((int)0x808F),
	ColorArrayPointer =  unchecked((int)0x8090),
	ColorArrayPointerExt =  unchecked((int)0x8090),
	IndexArrayPointer =  unchecked((int)0x8091),
	IndexArrayPointerExt =  unchecked((int)0x8091),
	TextureCoordArrayPointer =  unchecked((int)0x8092),
	TextureCoordArrayPointerExt =  unchecked((int)0x8092),
	EdgeFlagArrayPointer =  unchecked((int)0x8093),
	EdgeFlagArrayPointerExt =  unchecked((int)0x8093),
	InstrumentBufferPointerSgix =  unchecked((int)0x8180),
	DebugCallbackFunction =  unchecked((int)0x8244),
	DebugCallbackUserParam =  unchecked((int)0x8245),
}

#pragma warning restore

