/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GetTexBumpParameterATI
{
	BumpRotMatrixAti =  unchecked((int)0x8775),
	BumpRotMatrixSizeAti =  unchecked((int)0x8776),
	BumpNumTexUnitsAti =  unchecked((int)0x8777),
	BumpTexUnitsAti =  unchecked((int)0x8778),
}

#pragma warning restore

