/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GetVariantValueEXT
{
	VariantValueExt =  unchecked((int)0x87E4),
	VariantDatatypeExt =  unchecked((int)0x87E5),
	VariantArrayStrideExt =  unchecked((int)0x87E6),
	VariantArrayTypeExt =  unchecked((int)0x87E7),
}

#pragma warning restore

