/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum GraphicsResetStatus
{
	NoError =  unchecked((int)0),
	GuiltyContextReset =  unchecked((int)0x8253),
	InnocentContextReset =  unchecked((int)0x8254),
	UnknownContextReset =  unchecked((int)0x8255),
}

#pragma warning restore

