/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum HintTargetPGI
{
	VertexDataHintPgi =  unchecked((int)0x1A22A),
	VertexConsistentHintPgi =  unchecked((int)0x1A22B),
	MaterialSideHintPgi =  unchecked((int)0x1A22C),
	MaxVertexHintPgi =  unchecked((int)0x1A22D),
}

#pragma warning restore

