/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum HintMode
{
	DontCare =  unchecked((int)0x1100),
	Fastest =  unchecked((int)0x1101),
	Nicest =  unchecked((int)0x1102),
}

#pragma warning restore

