/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum HintTarget
{
	PerspectiveCorrectionHint =  unchecked((int)0x0C50),
	PointSmoothHint =  unchecked((int)0x0C51),
	LineSmoothHint =  unchecked((int)0x0C52),
	PolygonSmoothHint =  unchecked((int)0x0C53),
	FogHint =  unchecked((int)0x0C54),
	PackCmykHintExt =  unchecked((int)0x800E),
	UnpackCmykHintExt =  unchecked((int)0x800F),
	PhongHintWin =  unchecked((int)0x80EB),
	ClipVolumeClippingHintExt =  unchecked((int)0x80F0),
	TextureMultiBufferHintSgix =  unchecked((int)0x812E),
	GenerateMipmapHint =  unchecked((int)0x8192),
	GenerateMipmapHintSgis =  unchecked((int)0x8192),
	ProgramBinaryRetrievableHint =  unchecked((int)0x8257),
	ConvolutionHintSgix =  unchecked((int)0x8316),
	ScalebiasHintSgix =  unchecked((int)0x8322),
	LineQualityHintSgix =  unchecked((int)0x835B),
	VertexPreclipSgix =  unchecked((int)0x83EE),
	VertexPreclipHintSgix =  unchecked((int)0x83EF),
	TextureCompressionHint =  unchecked((int)0x84EF),
	TextureCompressionHintArb =  unchecked((int)0x84EF),
	VertexArrayStorageHintApple =  unchecked((int)0x851F),
	MultisampleFilterHintNv =  unchecked((int)0x8534),
	TransformHintApple =  unchecked((int)0x85B1),
	TextureStorageHintApple =  unchecked((int)0x85BC),
	FragmentShaderDerivativeHint =  unchecked((int)0x8B8B),
	FragmentShaderDerivativeHintArb =  unchecked((int)0x8B8B),
	FragmentShaderDerivativeHintOes =  unchecked((int)0x8B8B),
	BinningControlHintQcom =  unchecked((int)0x8FB0),
	PreferDoublebufferHintPgi =  unchecked((int)0x1A1F8),
	ConserveMemoryHintPgi =  unchecked((int)0x1A1FD),
	ReclaimMemoryHintPgi =  unchecked((int)0x1A1FE),
	NativeGraphicsBeginHintPgi =  unchecked((int)0x1A203),
	NativeGraphicsEndHintPgi =  unchecked((int)0x1A204),
	AlwaysFastHintPgi =  unchecked((int)0x1A20C),
	AlwaysSoftHintPgi =  unchecked((int)0x1A20D),
	AllowDrawObjHintPgi =  unchecked((int)0x1A20E),
	AllowDrawWinHintPgi =  unchecked((int)0x1A20F),
	AllowDrawFrgHintPgi =  unchecked((int)0x1A210),
	AllowDrawMemHintPgi =  unchecked((int)0x1A211),
	StrictDepthfuncHintPgi =  unchecked((int)0x1A216),
	StrictLightingHintPgi =  unchecked((int)0x1A217),
	StrictScissorHintPgi =  unchecked((int)0x1A218),
	FullStippleHintPgi =  unchecked((int)0x1A219),
	ClipNearHintPgi =  unchecked((int)0x1A220),
	ClipFarHintPgi =  unchecked((int)0x1A221),
	WideLineHintPgi =  unchecked((int)0x1A222),
	BackNormalsHintPgi =  unchecked((int)0x1A223),
	VertexDataHintPgi =  unchecked((int)0x1A22A),
	VertexConsistentHintPgi =  unchecked((int)0x1A22B),
	MaterialSideHintPgi =  unchecked((int)0x1A22C),
	MaxVertexHintPgi =  unchecked((int)0x1A22D),
}

#pragma warning restore

