/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ImageTransformPNameHP
{
	ImageScaleXHp =  unchecked((int)0x8155),
	ImageScaleYHp =  unchecked((int)0x8156),
	ImageTranslateXHp =  unchecked((int)0x8157),
	ImageTranslateYHp =  unchecked((int)0x8158),
	ImageRotateAngleHp =  unchecked((int)0x8159),
	ImageRotateOriginXHp =  unchecked((int)0x815A),
	ImageRotateOriginYHp =  unchecked((int)0x815B),
	ImageMagFilterHp =  unchecked((int)0x815C),
	ImageMinFilterHp =  unchecked((int)0x815D),
	ImageCubicWeightHp =  unchecked((int)0x815E),
}

#pragma warning restore

