/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum IndexFunctionEXT
{
	Never =  unchecked((int)0x0200),
	Less =  unchecked((int)0x0201),
	Equal =  unchecked((int)0x0202),
	Lequal =  unchecked((int)0x0203),
	Greater =  unchecked((int)0x0204),
	Notequal =  unchecked((int)0x0205),
	Gequal =  unchecked((int)0x0206),
	Always =  unchecked((int)0x0207),
}

#pragma warning restore

