/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum IndexPointerType
{
	Short =  unchecked((int)0x1402),
	Int =  unchecked((int)0x1404),
	Float =  unchecked((int)0x1406),
	Double =  unchecked((int)0x140A),
}

#pragma warning restore

