/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum InterleavedArrayFormat
{
	V2f =  unchecked((int)0x2A20),
	V3f =  unchecked((int)0x2A21),
	C4ubV2f =  unchecked((int)0x2A22),
	C4ubV3f =  unchecked((int)0x2A23),
	C3fV3f =  unchecked((int)0x2A24),
	N3fV3f =  unchecked((int)0x2A25),
	C4fN3fV3f =  unchecked((int)0x2A26),
	T2fV3f =  unchecked((int)0x2A27),
	T4fV4f =  unchecked((int)0x2A28),
	T2fC4ubV3f =  unchecked((int)0x2A29),
	T2fC3fV3f =  unchecked((int)0x2A2A),
	T2fN3fV3f =  unchecked((int)0x2A2B),
	T2fC4fN3fV3f =  unchecked((int)0x2A2C),
	T4fC4fN3fV4f =  unchecked((int)0x2A2D),
}

#pragma warning restore

