/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum LightTexturePNameEXT
{
	AttenuationExt =  unchecked((int)0x834D),
	ShadowAttenuationExt =  unchecked((int)0x834E),
}

#pragma warning restore

