/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum LightName
{
	Light0 =  unchecked((int)0x4000),
	Light1 =  unchecked((int)0x4001),
	Light2 =  unchecked((int)0x4002),
	Light3 =  unchecked((int)0x4003),
	Light4 =  unchecked((int)0x4004),
	Light5 =  unchecked((int)0x4005),
	Light6 =  unchecked((int)0x4006),
	Light7 =  unchecked((int)0x4007),
	FragmentLight0Sgix =  unchecked((int)0x840C),
	FragmentLight1Sgix =  unchecked((int)0x840D),
	FragmentLight2Sgix =  unchecked((int)0x840E),
	FragmentLight3Sgix =  unchecked((int)0x840F),
	FragmentLight4Sgix =  unchecked((int)0x8410),
	FragmentLight5Sgix =  unchecked((int)0x8411),
	FragmentLight6Sgix =  unchecked((int)0x8412),
	FragmentLight7Sgix =  unchecked((int)0x8413),
}

#pragma warning restore

