/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum LightModelParameter
{
	LightModelLocalViewer =  unchecked((int)0x0B51),
	LightModelTwoSide =  unchecked((int)0x0B52),
	LightModelAmbient =  unchecked((int)0x0B53),
	LightModelColorControl =  unchecked((int)0x81F8),
	LightModelColorControlExt =  unchecked((int)0x81F8),
}

#pragma warning restore

