/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum LightParameter
{
	Position =  unchecked((int)0x1203),
	SpotDirection =  unchecked((int)0x1204),
	SpotExponent =  unchecked((int)0x1205),
	SpotCutoff =  unchecked((int)0x1206),
	ConstantAttenuation =  unchecked((int)0x1207),
	LinearAttenuation =  unchecked((int)0x1208),
	QuadraticAttenuation =  unchecked((int)0x1209),
}

#pragma warning restore

