/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum LightEnvModeSGIX
{
	Add =  unchecked((int)0x0104),
	Replace =  unchecked((int)0x1E01),
	Modulate =  unchecked((int)0x2100),
}

#pragma warning restore

