/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum LightTextureModeEXT
{
	FragmentMaterialExt =  unchecked((int)0x8349),
	FragmentNormalExt =  unchecked((int)0x834A),
	FragmentColorExt =  unchecked((int)0x834C),
	FragmentDepth =  unchecked((int)0x8452),
	FragmentDepthExt =  unchecked((int)0x8452),
}

#pragma warning restore

