/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum LightModelColorControl
{
	SingleColor =  unchecked((int)0x81F9),
	SingleColorExt =  unchecked((int)0x81F9),
	SeparateSpecularColor =  unchecked((int)0x81FA),
	SeparateSpecularColorExt =  unchecked((int)0x81FA),
}

#pragma warning restore

