/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ListNameType
{
	Byte =  unchecked((int)0x1400),
	UnsignedByte =  unchecked((int)0x1401),
	Short =  unchecked((int)0x1402),
	UnsignedShort =  unchecked((int)0x1403),
	Int =  unchecked((int)0x1404),
	UnsignedInt =  unchecked((int)0x1405),
	Float =  unchecked((int)0x1406),
	2Bytes =  unchecked((int)0x1407),
	3Bytes =  unchecked((int)0x1408),
	4Bytes =  unchecked((int)0x1409),
}

#pragma warning restore

