/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum LogicOp
{
	Clear =  unchecked((int)0x1500),
	And =  unchecked((int)0x1501),
	AndReverse =  unchecked((int)0x1502),
	Copy =  unchecked((int)0x1503),
	AndInverted =  unchecked((int)0x1504),
	Noop =  unchecked((int)0x1505),
	Xor =  unchecked((int)0x1506),
	Or =  unchecked((int)0x1507),
	Nor =  unchecked((int)0x1508),
	Equiv =  unchecked((int)0x1509),
	Invert =  unchecked((int)0x150A),
	OrReverse =  unchecked((int)0x150B),
	CopyInverted =  unchecked((int)0x150C),
	OrInverted =  unchecked((int)0x150D),
	Nand =  unchecked((int)0x150E),
	Set =  unchecked((int)0x150F),
}

#pragma warning restore

