/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum MapAttribParameterNV
{
	MapAttribUOrderNv =  unchecked((int)0x86C3),
	MapAttribVOrderNv =  unchecked((int)0x86C4),
}

#pragma warning restore

