/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum MapBufferAccessMask
{
	MapReadBit =  unchecked((int)0x0001),
	MapReadBitExt =  unchecked((int)0x0001),
	MapWriteBit =  unchecked((int)0x0002),
	MapWriteBitExt =  unchecked((int)0x0002),
	MapInvalidateRangeBit =  unchecked((int)0x0004),
	MapInvalidateRangeBitExt =  unchecked((int)0x0004),
	MapInvalidateBufferBit =  unchecked((int)0x0008),
	MapInvalidateBufferBitExt =  unchecked((int)0x0008),
	MapFlushExplicitBit =  unchecked((int)0x0010),
	MapFlushExplicitBitExt =  unchecked((int)0x0010),
	MapUnsynchronizedBit =  unchecked((int)0x0020),
	MapUnsynchronizedBitExt =  unchecked((int)0x0020),
	MapPersistentBit =  unchecked((int)0x0040),
	MapPersistentBitExt =  unchecked((int)0x0040),
	MapCoherentBit =  unchecked((int)0x0080),
	MapCoherentBitExt =  unchecked((int)0x0080),
}

#pragma warning restore

