/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum MapTarget
{
	Map1Color4 =  unchecked((int)0x0D90),
	Map1Index =  unchecked((int)0x0D91),
	Map1Normal =  unchecked((int)0x0D92),
	Map1TextureCoord1 =  unchecked((int)0x0D93),
	Map1TextureCoord2 =  unchecked((int)0x0D94),
	Map1TextureCoord3 =  unchecked((int)0x0D95),
	Map1TextureCoord4 =  unchecked((int)0x0D96),
	Map1Vertex3 =  unchecked((int)0x0D97),
	Map1Vertex4 =  unchecked((int)0x0D98),
	Map2Color4 =  unchecked((int)0x0DB0),
	Map2Index =  unchecked((int)0x0DB1),
	Map2Normal =  unchecked((int)0x0DB2),
	Map2TextureCoord1 =  unchecked((int)0x0DB3),
	Map2TextureCoord2 =  unchecked((int)0x0DB4),
	Map2TextureCoord3 =  unchecked((int)0x0DB5),
	Map2TextureCoord4 =  unchecked((int)0x0DB6),
	Map2Vertex3 =  unchecked((int)0x0DB7),
	Map2Vertex4 =  unchecked((int)0x0DB8),
	GeometryDeformationSgix =  unchecked((int)0x8194),
	TextureDeformationSgix =  unchecked((int)0x8195),
}

#pragma warning restore

