/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum MapTextureFormatINTEL
{
	LayoutDefaultIntel =  unchecked((int)0),
	LayoutLinearIntel =  unchecked((int)1),
	LayoutLinearCpuCachedIntel =  unchecked((int)2),
}

#pragma warning restore

