/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum MatrixIndexPointerTypeARB
{
	UnsignedByte =  unchecked((int)0x1401),
	UnsignedShort =  unchecked((int)0x1403),
	UnsignedInt =  unchecked((int)0x1405),
}

#pragma warning restore

