/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum MatrixMode
{
	Modelview =  unchecked((int)0x1700),
	Modelview0Ext =  unchecked((int)0x1700),
	Projection =  unchecked((int)0x1701),
	Texture =  unchecked((int)0x1702),
}

#pragma warning restore

