/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum MemoryObjectParameterName
{
	DedicatedMemoryObjectExt =  unchecked((int)0x9581),
	ProtectedMemoryObjectExt =  unchecked((int)0x959B),
}

#pragma warning restore

