/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum MemoryBarrierMask
{
	VertexAttribArrayBarrierBit =  unchecked((int)0x00000001),
	VertexAttribArrayBarrierBitExt =  unchecked((int)0x00000001),
	ElementArrayBarrierBit =  unchecked((int)0x00000002),
	ElementArrayBarrierBitExt =  unchecked((int)0x00000002),
	UniformBarrierBit =  unchecked((int)0x00000004),
	UniformBarrierBitExt =  unchecked((int)0x00000004),
	TextureFetchBarrierBit =  unchecked((int)0x00000008),
	TextureFetchBarrierBitExt =  unchecked((int)0x00000008),
	ShaderGlobalAccessBarrierBitNv =  unchecked((int)0x00000010),
	ShaderImageAccessBarrierBit =  unchecked((int)0x00000020),
	ShaderImageAccessBarrierBitExt =  unchecked((int)0x00000020),
	CommandBarrierBit =  unchecked((int)0x00000040),
	CommandBarrierBitExt =  unchecked((int)0x00000040),
	PixelBufferBarrierBit =  unchecked((int)0x00000080),
	PixelBufferBarrierBitExt =  unchecked((int)0x00000080),
	TextureUpdateBarrierBit =  unchecked((int)0x00000100),
	TextureUpdateBarrierBitExt =  unchecked((int)0x00000100),
	BufferUpdateBarrierBit =  unchecked((int)0x00000200),
	BufferUpdateBarrierBitExt =  unchecked((int)0x00000200),
	FramebufferBarrierBit =  unchecked((int)0x00000400),
	FramebufferBarrierBitExt =  unchecked((int)0x00000400),
	TransformFeedbackBarrierBit =  unchecked((int)0x00000800),
	TransformFeedbackBarrierBitExt =  unchecked((int)0x00000800),
	AtomicCounterBarrierBit =  unchecked((int)0x00001000),
	AtomicCounterBarrierBitExt =  unchecked((int)0x00001000),
	ShaderStorageBarrierBit =  unchecked((int)0x00002000),
	ClientMappedBufferBarrierBit =  unchecked((int)0x00004000),
	ClientMappedBufferBarrierBitExt =  unchecked((int)0x00004000),
	QueryBufferBarrierBit =  unchecked((int)0x00008000),
	AllBarrierBits =  unchecked((int)0xFFFFFFFF),
	AllBarrierBitsExt =  unchecked((int)0xFFFFFFFF),
}

#pragma warning restore

