/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum NormalPointerType
{
	Byte =  unchecked((int)0x1400),
	Short =  unchecked((int)0x1402),
	Int =  unchecked((int)0x1404),
	Float =  unchecked((int)0x1406),
	Double =  unchecked((int)0x140A),
}

#pragma warning restore

