/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ObjectTypeAPPLE
{
	DrawPixelsApple =  unchecked((int)0x8A0A),
	FenceApple =  unchecked((int)0x8A0B),
}

#pragma warning restore

