/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ObjectIdentifier
{
	Texture =  unchecked((int)0x1702),
	VertexArray =  unchecked((int)0x8074),
	Buffer =  unchecked((int)0x82E0),
	Shader =  unchecked((int)0x82E1),
	Program =  unchecked((int)0x82E2),
	Query =  unchecked((int)0x82E3),
	ProgramPipeline =  unchecked((int)0x82E4),
	Sampler =  unchecked((int)0x82E6),
	Framebuffer =  unchecked((int)0x8D40),
	Renderbuffer =  unchecked((int)0x8D41),
	TransformFeedback =  unchecked((int)0x8E22),
}

#pragma warning restore

