/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum OcclusionQueryEventMaskAMD
{
	QueryDepthPassEventBitAmd =  unchecked((int)0x00000001),
	QueryDepthFailEventBitAmd =  unchecked((int)0x00000002),
	QueryStencilFailEventBitAmd =  unchecked((int)0x00000004),
	QueryDepthBoundsFailEventBitAmd =  unchecked((int)0x00000008),
	QueryAllEventBitsAmd =  unchecked((int)0xFFFFFFFF),
}

#pragma warning restore

