/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum OcclusionQueryParameterNameNV
{
	PixelCountNv =  unchecked((int)0x8866),
	PixelCountAvailableNv =  unchecked((int)0x8867),
}

#pragma warning restore

