/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ParameterRangeEXT
{
	NormalizedRangeExt =  unchecked((int)0x87E0),
	FullRangeExt =  unchecked((int)0x87E1),
}

#pragma warning restore

