/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PatchParameterName
{
	PatchVertices =  unchecked((int)0x8E72),
	PatchDefaultInnerLevel =  unchecked((int)0x8E73),
	PatchDefaultOuterLevel =  unchecked((int)0x8E74),
}

#pragma warning restore

