/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PathCoordType
{
	ClosePathNv =  unchecked((int)0x00),
	MoveToNv =  unchecked((int)0x02),
	RelativeMoveToNv =  unchecked((int)0x03),
	LineToNv =  unchecked((int)0x04),
	RelativeLineToNv =  unchecked((int)0x05),
	HorizontalLineToNv =  unchecked((int)0x06),
	RelativeHorizontalLineToNv =  unchecked((int)0x07),
	VerticalLineToNv =  unchecked((int)0x08),
	RelativeVerticalLineToNv =  unchecked((int)0x09),
	QuadraticCurveToNv =  unchecked((int)0x0A),
	RelativeQuadraticCurveToNv =  unchecked((int)0x0B),
	CubicCurveToNv =  unchecked((int)0x0C),
	RelativeCubicCurveToNv =  unchecked((int)0x0D),
	SmoothQuadraticCurveToNv =  unchecked((int)0x0E),
	RelativeSmoothQuadraticCurveToNv =  unchecked((int)0x0F),
	SmoothCubicCurveToNv =  unchecked((int)0x10),
	RelativeSmoothCubicCurveToNv =  unchecked((int)0x11),
	SmallCcwArcToNv =  unchecked((int)0x12),
	RelativeSmallCcwArcToNv =  unchecked((int)0x13),
	SmallCwArcToNv =  unchecked((int)0x14),
	RelativeSmallCwArcToNv =  unchecked((int)0x15),
	LargeCcwArcToNv =  unchecked((int)0x16),
	RelativeLargeCcwArcToNv =  unchecked((int)0x17),
	LargeCwArcToNv =  unchecked((int)0x18),
	RelativeLargeCwArcToNv =  unchecked((int)0x19),
	ConicCurveToNv =  unchecked((int)0x1A),
	RelativeConicCurveToNv =  unchecked((int)0x1B),
	RoundedRectNv =  unchecked((int)0xE8),
	RelativeRoundedRectNv =  unchecked((int)0xE9),
	RoundedRect2Nv =  unchecked((int)0xEA),
	RelativeRoundedRect2Nv =  unchecked((int)0xEB),
	RoundedRect4Nv =  unchecked((int)0xEC),
	RelativeRoundedRect4Nv =  unchecked((int)0xED),
	RoundedRect8Nv =  unchecked((int)0xEE),
	RelativeRoundedRect8Nv =  unchecked((int)0xEF),
	RestartPathNv =  unchecked((int)0xF0),
	DupFirstCubicCurveToNv =  unchecked((int)0xF2),
	DupLastCubicCurveToNv =  unchecked((int)0xF4),
	RectNv =  unchecked((int)0xF6),
	RelativeRectNv =  unchecked((int)0xF7),
	CircularCcwArcToNv =  unchecked((int)0xF8),
	CircularCwArcToNv =  unchecked((int)0xFA),
	CircularTangentArcToNv =  unchecked((int)0xFC),
	ArcToNv =  unchecked((int)0xFE),
	RelativeArcToNv =  unchecked((int)0xFF),
}

#pragma warning restore

