/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PathElementType
{
	Utf8Nv =  unchecked((int)0x909A),
	Utf16Nv =  unchecked((int)0x909B),
}

#pragma warning restore

