/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PathFillMode
{
	Invert =  unchecked((int)0x150A),
	PathFillModeNv =  unchecked((int)0x9080),
	CountUpNv =  unchecked((int)0x9088),
	CountDownNv =  unchecked((int)0x9089),
}

#pragma warning restore

