/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PathHandleMissingGlyphs
{
	SkipMissingGlyphNv =  unchecked((int)0x90A9),
	UseMissingGlyphNv =  unchecked((int)0x90AA),
}

#pragma warning restore

