/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PathColor
{
	PrimaryColorNv =  unchecked((int)0x852C),
	SecondaryColorNv =  unchecked((int)0x852D),
	PrimaryColor =  unchecked((int)0x8577),
}

#pragma warning restore

