/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PathParameter
{
	PathStrokeWidthNv =  unchecked((int)0x9075),
	PathEndCapsNv =  unchecked((int)0x9076),
	PathInitialEndCapNv =  unchecked((int)0x9077),
	PathTerminalEndCapNv =  unchecked((int)0x9078),
	PathJoinStyleNv =  unchecked((int)0x9079),
	PathMiterLimitNv =  unchecked((int)0x907A),
	PathDashCapsNv =  unchecked((int)0x907B),
	PathInitialDashCapNv =  unchecked((int)0x907C),
	PathTerminalDashCapNv =  unchecked((int)0x907D),
	PathDashOffsetNv =  unchecked((int)0x907E),
	PathClientLengthNv =  unchecked((int)0x907F),
	PathFillModeNv =  unchecked((int)0x9080),
	PathFillMaskNv =  unchecked((int)0x9081),
	PathFillCoverModeNv =  unchecked((int)0x9082),
	PathStrokeCoverModeNv =  unchecked((int)0x9083),
	PathStrokeMaskNv =  unchecked((int)0x9084),
	PathObjectBoundingBoxNv =  unchecked((int)0x908A),
	PathCommandCountNv =  unchecked((int)0x909D),
	PathCoordCountNv =  unchecked((int)0x909E),
	PathDashArrayCountNv =  unchecked((int)0x909F),
	PathComputedLengthNv =  unchecked((int)0x90A0),
	PathFillBoundingBoxNv =  unchecked((int)0x90A1),
	PathStrokeBoundingBoxNv =  unchecked((int)0x90A2),
	PathDashOffsetResetNv =  unchecked((int)0x90B4),
}

#pragma warning restore

