/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PathTransformType
{
	None =  unchecked((int)0),
	TranslateXNv =  unchecked((int)0x908E),
	TranslateYNv =  unchecked((int)0x908F),
	Translate2dNv =  unchecked((int)0x9090),
	Translate3dNv =  unchecked((int)0x9091),
	Affine2dNv =  unchecked((int)0x9092),
	Affine3dNv =  unchecked((int)0x9094),
	TransposeAffine2dNv =  unchecked((int)0x9096),
	TransposeAffine3dNv =  unchecked((int)0x9098),
}

#pragma warning restore

