/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PathFontStyle
{
	BoldBitNv =  unchecked((int)0x01),
	ItalicBitNv =  unchecked((int)0x02),
	None =  unchecked((int)0),
}

#pragma warning restore

