/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PathColorFormat
{
	None =  unchecked((int)0),
	Alpha =  unchecked((int)0x1906),
	Rgb =  unchecked((int)0x1907),
	Rgba =  unchecked((int)0x1908),
	Luminance =  unchecked((int)0x1909),
	LuminanceAlpha =  unchecked((int)0x190A),
	Intensity =  unchecked((int)0x8049),
}

#pragma warning restore

