/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PathGenMode
{
	None =  unchecked((int)0),
	EyeLinear =  unchecked((int)0x2400),
	ObjectLinear =  unchecked((int)0x2401),
	Constant =  unchecked((int)0x8576),
	PathObjectBoundingBoxNv =  unchecked((int)0x908A),
}

#pragma warning restore

