/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PathFontTarget
{
	StandardFontNameNv =  unchecked((int)0x9072),
	SystemFontNameNv =  unchecked((int)0x9073),
	FileNameNv =  unchecked((int)0x9074),
}

#pragma warning restore

