/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PathMetricMask
{
	GlyphWidthBitNv =  unchecked((int)0x01),
	GlyphHeightBitNv =  unchecked((int)0x02),
	GlyphHorizontalBearingXBitNv =  unchecked((int)0x04),
	GlyphHorizontalBearingYBitNv =  unchecked((int)0x08),
	GlyphHorizontalBearingAdvanceBitNv =  unchecked((int)0x10),
	GlyphVerticalBearingXBitNv =  unchecked((int)0x20),
	GlyphVerticalBearingYBitNv =  unchecked((int)0x40),
	GlyphVerticalBearingAdvanceBitNv =  unchecked((int)0x80),
	GlyphHasKerningBitNv =  unchecked((int)0x100),
	FontXMinBoundsBitNv =  unchecked((int)0x00010000),
	FontYMinBoundsBitNv =  unchecked((int)0x00020000),
	FontXMaxBoundsBitNv =  unchecked((int)0x00040000),
	FontYMaxBoundsBitNv =  unchecked((int)0x00080000),
	FontUnitsPerEmBitNv =  unchecked((int)0x00100000),
	FontAscenderBitNv =  unchecked((int)0x00200000),
	FontDescenderBitNv =  unchecked((int)0x00400000),
	FontHeightBitNv =  unchecked((int)0x00800000),
	FontMaxAdvanceWidthBitNv =  unchecked((int)0x01000000),
	FontMaxAdvanceHeightBitNv =  unchecked((int)0x02000000),
	FontUnderlinePositionBitNv =  unchecked((int)0x04000000),
	FontUnderlineThicknessBitNv =  unchecked((int)0x08000000),
	FontHasKerningBitNv =  unchecked((int)0x10000000),
	FontNumGlyphIndicesBitNv =  unchecked((int)0x20000000),
}

#pragma warning restore

