/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PipelineParameterName
{
	ActiveProgram =  unchecked((int)0x8259),
	FragmentShader =  unchecked((int)0x8B30),
	VertexShader =  unchecked((int)0x8B31),
	InfoLogLength =  unchecked((int)0x8B84),
	GeometryShader =  unchecked((int)0x8DD9),
	TessEvaluationShader =  unchecked((int)0x8E87),
	TessControlShader =  unchecked((int)0x8E88),
}

#pragma warning restore

