/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PixelStoreResampleMode
{
	ResampleDecimateSgix =  unchecked((int)0x8430),
	ResampleReplicateSgix =  unchecked((int)0x8433),
	ResampleZeroFillSgix =  unchecked((int)0x8434),
}

#pragma warning restore

