/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PixelStoreParameter
{
	UnpackSwapBytes =  unchecked((int)0x0CF0),
	UnpackLsbFirst =  unchecked((int)0x0CF1),
	UnpackRowLength =  unchecked((int)0x0CF2),
	UnpackRowLengthExt =  unchecked((int)0x0CF2),
	UnpackSkipRows =  unchecked((int)0x0CF3),
	UnpackSkipRowsExt =  unchecked((int)0x0CF3),
	UnpackSkipPixels =  unchecked((int)0x0CF4),
	UnpackSkipPixelsExt =  unchecked((int)0x0CF4),
	UnpackAlignment =  unchecked((int)0x0CF5),
	PackSwapBytes =  unchecked((int)0x0D00),
	PackLsbFirst =  unchecked((int)0x0D01),
	PackRowLength =  unchecked((int)0x0D02),
	PackRowLengthNv =  unchecked((int)0x0D02),
	PackSkipRows =  unchecked((int)0x0D03),
	PackSkipRowsNv =  unchecked((int)0x0D03),
	PackSkipPixels =  unchecked((int)0x0D04),
	PackSkipPixelsNv =  unchecked((int)0x0D04),
	PackAlignment =  unchecked((int)0x0D05),
	PackSkipImages =  unchecked((int)0x806B),
	PackSkipImagesExt =  unchecked((int)0x806B),
	PackImageHeight =  unchecked((int)0x806C),
	PackImageHeightExt =  unchecked((int)0x806C),
	UnpackSkipImages =  unchecked((int)0x806D),
	UnpackSkipImagesExt =  unchecked((int)0x806D),
	UnpackImageHeight =  unchecked((int)0x806E),
	UnpackImageHeightExt =  unchecked((int)0x806E),
	PackSkipVolumesSgis =  unchecked((int)0x8130),
	PackImageDepthSgis =  unchecked((int)0x8131),
	UnpackSkipVolumesSgis =  unchecked((int)0x8132),
	UnpackImageDepthSgis =  unchecked((int)0x8133),
	PixelTileWidthSgix =  unchecked((int)0x8140),
	PixelTileHeightSgix =  unchecked((int)0x8141),
	PixelTileGridWidthSgix =  unchecked((int)0x8142),
	PixelTileGridHeightSgix =  unchecked((int)0x8143),
	PixelTileGridDepthSgix =  unchecked((int)0x8144),
	PixelTileCacheSizeSgix =  unchecked((int)0x8145),
	PackResampleSgix =  unchecked((int)0x842E),
	UnpackResampleSgix =  unchecked((int)0x842F),
	PackSubsampleRateSgix =  unchecked((int)0x85A0),
	UnpackSubsampleRateSgix =  unchecked((int)0x85A1),
	PackResampleOml =  unchecked((int)0x8984),
	UnpackResampleOml =  unchecked((int)0x8985),
}

#pragma warning restore

