/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PixelMap
{
	PixelMapIToI =  unchecked((int)0x0C70),
	PixelMapSToS =  unchecked((int)0x0C71),
	PixelMapIToR =  unchecked((int)0x0C72),
	PixelMapIToG =  unchecked((int)0x0C73),
	PixelMapIToB =  unchecked((int)0x0C74),
	PixelMapIToA =  unchecked((int)0x0C75),
	PixelMapRToR =  unchecked((int)0x0C76),
	PixelMapGToG =  unchecked((int)0x0C77),
	PixelMapBToB =  unchecked((int)0x0C78),
	PixelMapAToA =  unchecked((int)0x0C79),
}

#pragma warning restore

