/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PixelFormat
{
	UnsignedShort =  unchecked((int)0x1403),
	UnsignedInt =  unchecked((int)0x1405),
	ColorIndex =  unchecked((int)0x1900),
	StencilIndex =  unchecked((int)0x1901),
	DepthComponent =  unchecked((int)0x1902),
	Red =  unchecked((int)0x1903),
	RedExt =  unchecked((int)0x1903),
	Green =  unchecked((int)0x1904),
	Blue =  unchecked((int)0x1905),
	Alpha =  unchecked((int)0x1906),
	Rgb =  unchecked((int)0x1907),
	Rgba =  unchecked((int)0x1908),
	Luminance =  unchecked((int)0x1909),
	LuminanceAlpha =  unchecked((int)0x190A),
	AbgrExt =  unchecked((int)0x8000),
	CmykExt =  unchecked((int)0x800C),
	CmykaExt =  unchecked((int)0x800D),
	Bgr =  unchecked((int)0x80E0),
	BgrExt =  unchecked((int)0x80E0),
	Bgra =  unchecked((int)0x80E1),
	BgraExt =  unchecked((int)0x80E1),
	BgraImg =  unchecked((int)0x80E1),
	Ycrcb422Sgix =  unchecked((int)0x81BB),
	Ycrcb444Sgix =  unchecked((int)0x81BC),
	Rg =  unchecked((int)0x8227),
	RgInteger =  unchecked((int)0x8228),
	DepthStencil =  unchecked((int)0x84F9),
	RedInteger =  unchecked((int)0x8D94),
	GreenInteger =  unchecked((int)0x8D95),
	BlueInteger =  unchecked((int)0x8D96),
	RgbInteger =  unchecked((int)0x8D98),
	RgbaInteger =  unchecked((int)0x8D99),
	BgrInteger =  unchecked((int)0x8D9A),
	BgraInteger =  unchecked((int)0x8D9B),
}

#pragma warning restore

