/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PixelTransferParameter
{
	MapColor =  unchecked((int)0x0D10),
	MapStencil =  unchecked((int)0x0D11),
	IndexShift =  unchecked((int)0x0D12),
	IndexOffset =  unchecked((int)0x0D13),
	RedScale =  unchecked((int)0x0D14),
	RedBias =  unchecked((int)0x0D15),
	GreenScale =  unchecked((int)0x0D18),
	GreenBias =  unchecked((int)0x0D19),
	BlueScale =  unchecked((int)0x0D1A),
	BlueBias =  unchecked((int)0x0D1B),
	AlphaScale =  unchecked((int)0x0D1C),
	AlphaBias =  unchecked((int)0x0D1D),
	DepthScale =  unchecked((int)0x0D1E),
	DepthBias =  unchecked((int)0x0D1F),
	PostConvolutionRedScale =  unchecked((int)0x801C),
	PostConvolutionRedScaleExt =  unchecked((int)0x801C),
	PostConvolutionGreenScale =  unchecked((int)0x801D),
	PostConvolutionGreenScaleExt =  unchecked((int)0x801D),
	PostConvolutionBlueScale =  unchecked((int)0x801E),
	PostConvolutionBlueScaleExt =  unchecked((int)0x801E),
	PostConvolutionAlphaScale =  unchecked((int)0x801F),
	PostConvolutionAlphaScaleExt =  unchecked((int)0x801F),
	PostConvolutionRedBias =  unchecked((int)0x8020),
	PostConvolutionRedBiasExt =  unchecked((int)0x8020),
	PostConvolutionGreenBias =  unchecked((int)0x8021),
	PostConvolutionGreenBiasExt =  unchecked((int)0x8021),
	PostConvolutionBlueBias =  unchecked((int)0x8022),
	PostConvolutionBlueBiasExt =  unchecked((int)0x8022),
	PostConvolutionAlphaBias =  unchecked((int)0x8023),
	PostConvolutionAlphaBiasExt =  unchecked((int)0x8023),
	PostColorMatrixRedScale =  unchecked((int)0x80B4),
	PostColorMatrixRedScaleSgi =  unchecked((int)0x80B4),
	PostColorMatrixGreenScale =  unchecked((int)0x80B5),
	PostColorMatrixGreenScaleSgi =  unchecked((int)0x80B5),
	PostColorMatrixBlueScale =  unchecked((int)0x80B6),
	PostColorMatrixBlueScaleSgi =  unchecked((int)0x80B6),
	PostColorMatrixAlphaScale =  unchecked((int)0x80B7),
	PostColorMatrixAlphaScaleSgi =  unchecked((int)0x80B7),
	PostColorMatrixRedBias =  unchecked((int)0x80B8),
	PostColorMatrixRedBiasSgi =  unchecked((int)0x80B8),
	PostColorMatrixGreenBias =  unchecked((int)0x80B9),
	PostColorMatrixGreenBiasSgi =  unchecked((int)0x80B9),
	PostColorMatrixBlueBias =  unchecked((int)0x80BA),
	PostColorMatrixBlueBiasSgi =  unchecked((int)0x80BA),
	PostColorMatrixAlphaBias =  unchecked((int)0x80BB),
	PostColorMatrixAlphaBiasSgi =  unchecked((int)0x80BB),
}

#pragma warning restore

