/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PixelType
{
	Byte =  unchecked((int)0x1400),
	UnsignedByte =  unchecked((int)0x1401),
	Short =  unchecked((int)0x1402),
	UnsignedShort =  unchecked((int)0x1403),
	Int =  unchecked((int)0x1404),
	UnsignedInt =  unchecked((int)0x1405),
	Float =  unchecked((int)0x1406),
	HalfFloat =  unchecked((int)0x140B),
	HalfFloatArb =  unchecked((int)0x140B),
	HalfFloatNv =  unchecked((int)0x140B),
	HalfApple =  unchecked((int)0x140B),
	Bitmap =  unchecked((int)0x1A00),
	UnsignedByte332 =  unchecked((int)0x8032),
	UnsignedByte332Ext =  unchecked((int)0x8032),
	UnsignedShort4444 =  unchecked((int)0x8033),
	UnsignedShort4444Ext =  unchecked((int)0x8033),
	UnsignedShort5551 =  unchecked((int)0x8034),
	UnsignedShort5551Ext =  unchecked((int)0x8034),
	UnsignedInt8888 =  unchecked((int)0x8035),
	UnsignedInt8888Ext =  unchecked((int)0x8035),
	UnsignedInt1010102 =  unchecked((int)0x8036),
	UnsignedInt1010102Ext =  unchecked((int)0x8036),
	UnsignedByte233Rev =  unchecked((int)0x8362),
	UnsignedByte233RevExt =  unchecked((int)0x8362),
	UnsignedShort565 =  unchecked((int)0x8363),
	UnsignedShort565Ext =  unchecked((int)0x8363),
	UnsignedShort565Rev =  unchecked((int)0x8364),
	UnsignedShort565RevExt =  unchecked((int)0x8364),
	UnsignedShort4444Rev =  unchecked((int)0x8365),
	UnsignedShort4444RevExt =  unchecked((int)0x8365),
	UnsignedShort4444RevImg =  unchecked((int)0x8365),
	UnsignedShort1555Rev =  unchecked((int)0x8366),
	UnsignedShort1555RevExt =  unchecked((int)0x8366),
	UnsignedInt8888Rev =  unchecked((int)0x8367),
	UnsignedInt8888RevExt =  unchecked((int)0x8367),
	UnsignedInt2101010Rev =  unchecked((int)0x8368),
	UnsignedInt2101010RevExt =  unchecked((int)0x8368),
	UnsignedInt248 =  unchecked((int)0x84FA),
	UnsignedInt248Ext =  unchecked((int)0x84FA),
	UnsignedInt248Nv =  unchecked((int)0x84FA),
	UnsignedInt248Oes =  unchecked((int)0x84FA),
	UnsignedInt10f11f11fRev =  unchecked((int)0x8C3B),
	UnsignedInt10f11f11fRevApple =  unchecked((int)0x8C3B),
	UnsignedInt10f11f11fRevExt =  unchecked((int)0x8C3B),
	UnsignedInt5999Rev =  unchecked((int)0x8C3E),
	UnsignedInt5999RevApple =  unchecked((int)0x8C3E),
	UnsignedInt5999RevExt =  unchecked((int)0x8C3E),
	Float32UnsignedInt248Rev =  unchecked((int)0x8DAD),
	Float32UnsignedInt248RevNv =  unchecked((int)0x8DAD),
}

#pragma warning restore

