/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PixelStoreSubsampleRate
{
	PixelSubsample4444Sgix =  unchecked((int)0x85A2),
	PixelSubsample2424Sgix =  unchecked((int)0x85A3),
	PixelSubsample4242Sgix =  unchecked((int)0x85A4),
}

#pragma warning restore

