/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PixelDataRangeTargetNV
{
	WritePixelDataRangeNv =  unchecked((int)0x8878),
	ReadPixelDataRangeNv =  unchecked((int)0x8879),
}

#pragma warning restore

