/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PixelTexGenModeSGIX
{
	None =  unchecked((int)0),
	Alpha =  unchecked((int)0x1906),
	Rgb =  unchecked((int)0x1907),
	Rgba =  unchecked((int)0x1908),
	PixelTexGenQCeilingSgix =  unchecked((int)0x8184),
	PixelTexGenQRoundSgix =  unchecked((int)0x8185),
	PixelTexGenQFloorSgix =  unchecked((int)0x8186),
	PixelTexGenAlphaLsSgix =  unchecked((int)0x8189),
	PixelTexGenAlphaMsSgix =  unchecked((int)0x818A),
}

#pragma warning restore

