/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PixelTransformPNameEXT
{
	PixelMagFilterExt =  unchecked((int)0x8331),
	PixelMinFilterExt =  unchecked((int)0x8332),
	PixelCubicWeightExt =  unchecked((int)0x8333),
}

#pragma warning restore

