/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PixelTexGenParameterNameSGIS
{
	PixelFragmentRgbSourceSgis =  unchecked((int)0x8354),
	PixelFragmentAlphaSourceSgis =  unchecked((int)0x8355),
}

#pragma warning restore

