/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PNTrianglesPNameATI
{
	PnTrianglesPointModeAti =  unchecked((int)0x87F2),
	PnTrianglesNormalModeAti =  unchecked((int)0x87F3),
	PnTrianglesTesselationLevelAti =  unchecked((int)0x87F4),
}

#pragma warning restore

