/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PointParameterNameARB
{
	PointSizeMin =  unchecked((int)0x8126),
	PointSizeMinArb =  unchecked((int)0x8126),
	PointSizeMinExt =  unchecked((int)0x8126),
	PointSizeMinSgis =  unchecked((int)0x8126),
	PointSizeMax =  unchecked((int)0x8127),
	PointSizeMaxArb =  unchecked((int)0x8127),
	PointSizeMaxExt =  unchecked((int)0x8127),
	PointSizeMaxSgis =  unchecked((int)0x8127),
	PointFadeThresholdSize =  unchecked((int)0x8128),
	PointFadeThresholdSizeArb =  unchecked((int)0x8128),
	PointFadeThresholdSizeExt =  unchecked((int)0x8128),
	PointFadeThresholdSizeSgis =  unchecked((int)0x8128),
	DistanceAttenuationExt =  unchecked((int)0x8129),
	DistanceAttenuationSgis =  unchecked((int)0x8129),
	PointDistanceAttenuation =  unchecked((int)0x8129),
	PointDistanceAttenuationArb =  unchecked((int)0x8129),
}

#pragma warning restore

