/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PolygonMode
{
	Point =  unchecked((int)0x1B00),
	Line =  unchecked((int)0x1B01),
	Fill =  unchecked((int)0x1B02),
}

#pragma warning restore

