/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PrecisionType
{
	LowFloat =  unchecked((int)0x8DF0),
	MediumFloat =  unchecked((int)0x8DF1),
	HighFloat =  unchecked((int)0x8DF2),
	LowInt =  unchecked((int)0x8DF3),
	MediumInt =  unchecked((int)0x8DF4),
	HighInt =  unchecked((int)0x8DF5),
}

#pragma warning restore

