/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PreserveModeATI
{
	PreserveAti =  unchecked((int)0x8762),
	DiscardAti =  unchecked((int)0x8763),
}

#pragma warning restore

