/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum PrimitiveType
{
	Points =  unchecked((int)0x0000),
	Lines =  unchecked((int)0x0001),
	LineLoop =  unchecked((int)0x0002),
	LineStrip =  unchecked((int)0x0003),
	Triangles =  unchecked((int)0x0004),
	TriangleStrip =  unchecked((int)0x0005),
	TriangleFan =  unchecked((int)0x0006),
	Quads =  unchecked((int)0x0007),
	QuadsExt =  unchecked((int)0x0007),
	QuadStrip =  unchecked((int)0x0008),
	Polygon =  unchecked((int)0x0009),
	LinesAdjacency =  unchecked((int)0x000A),
	LinesAdjacencyArb =  unchecked((int)0x000A),
	LinesAdjacencyExt =  unchecked((int)0x000A),
	LineStripAdjacency =  unchecked((int)0x000B),
	LineStripAdjacencyArb =  unchecked((int)0x000B),
	LineStripAdjacencyExt =  unchecked((int)0x000B),
	TrianglesAdjacency =  unchecked((int)0x000C),
	TrianglesAdjacencyArb =  unchecked((int)0x000C),
	TrianglesAdjacencyExt =  unchecked((int)0x000C),
	TriangleStripAdjacency =  unchecked((int)0x000D),
	TriangleStripAdjacencyArb =  unchecked((int)0x000D),
	TriangleStripAdjacencyExt =  unchecked((int)0x000D),
	Patches =  unchecked((int)0x000E),
	PatchesExt =  unchecked((int)0x000E),
}

#pragma warning restore

