/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ProgramPropertyARB
{
	ComputeWorkGroupSize =  unchecked((int)0x8267),
	ProgramBinaryLength =  unchecked((int)0x8741),
	GeometryVerticesOut =  unchecked((int)0x8916),
	GeometryInputType =  unchecked((int)0x8917),
	GeometryOutputType =  unchecked((int)0x8918),
	ActiveUniformBlockMaxNameLength =  unchecked((int)0x8A35),
	ActiveUniformBlocks =  unchecked((int)0x8A36),
	DeleteStatus =  unchecked((int)0x8B80),
	LinkStatus =  unchecked((int)0x8B82),
	ValidateStatus =  unchecked((int)0x8B83),
	InfoLogLength =  unchecked((int)0x8B84),
	AttachedShaders =  unchecked((int)0x8B85),
	ActiveUniforms =  unchecked((int)0x8B86),
	ActiveUniformMaxLength =  unchecked((int)0x8B87),
	ActiveAttributes =  unchecked((int)0x8B89),
	ActiveAttributeMaxLength =  unchecked((int)0x8B8A),
	TransformFeedbackVaryingMaxLength =  unchecked((int)0x8C76),
	TransformFeedbackBufferMode =  unchecked((int)0x8C7F),
	TransformFeedbackVaryings =  unchecked((int)0x8C83),
	ActiveAtomicCounterBuffers =  unchecked((int)0x92D9),
}

#pragma warning restore

