/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ProgramStagePName
{
	ActiveSubroutines =  unchecked((int)0x8DE5),
	ActiveSubroutineUniforms =  unchecked((int)0x8DE6),
	ActiveSubroutineUniformLocations =  unchecked((int)0x8E47),
	ActiveSubroutineMaxLength =  unchecked((int)0x8E48),
	ActiveSubroutineUniformMaxLength =  unchecked((int)0x8E49),
}

#pragma warning restore

