/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ProgramTarget
{
	TextFragmentShaderAti =  unchecked((int)0x8200),
	VertexProgramArb =  unchecked((int)0x8620),
	FragmentProgramArb =  unchecked((int)0x8804),
	TessControlProgramNv =  unchecked((int)0x891E),
	TessEvaluationProgramNv =  unchecked((int)0x891F),
	GeometryProgramNv =  unchecked((int)0x8C26),
	ComputeProgramNv =  unchecked((int)0x90FB),
}

#pragma warning restore

