/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ProgramInterface
{
	TransformFeedbackBuffer =  unchecked((int)0x8C8E),
	Uniform =  unchecked((int)0x92E1),
	UniformBlock =  unchecked((int)0x92E2),
	ProgramInput =  unchecked((int)0x92E3),
	ProgramOutput =  unchecked((int)0x92E4),
	BufferVariable =  unchecked((int)0x92E5),
	ShaderStorageBlock =  unchecked((int)0x92E6),
	VertexSubroutine =  unchecked((int)0x92E8),
	TessControlSubroutine =  unchecked((int)0x92E9),
	TessEvaluationSubroutine =  unchecked((int)0x92EA),
	GeometrySubroutine =  unchecked((int)0x92EB),
	FragmentSubroutine =  unchecked((int)0x92EC),
	ComputeSubroutine =  unchecked((int)0x92ED),
	VertexSubroutineUniform =  unchecked((int)0x92EE),
	TessControlSubroutineUniform =  unchecked((int)0x92EF),
	TessEvaluationSubroutineUniform =  unchecked((int)0x92F0),
	GeometrySubroutineUniform =  unchecked((int)0x92F1),
	FragmentSubroutineUniform =  unchecked((int)0x92F2),
	ComputeSubroutineUniform =  unchecked((int)0x92F3),
	TransformFeedbackVarying =  unchecked((int)0x92F4),
}

#pragma warning restore

