/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ProgramResourceProperty
{
	NumCompatibleSubroutines =  unchecked((int)0x8E4A),
	CompatibleSubroutines =  unchecked((int)0x8E4B),
	Uniform =  unchecked((int)0x92E1),
	IsPerPatch =  unchecked((int)0x92E7),
	NameLength =  unchecked((int)0x92F9),
	Type =  unchecked((int)0x92FA),
	ArraySize =  unchecked((int)0x92FB),
	Offset =  unchecked((int)0x92FC),
	BlockIndex =  unchecked((int)0x92FD),
	ArrayStride =  unchecked((int)0x92FE),
	MatrixStride =  unchecked((int)0x92FF),
	IsRowMajor =  unchecked((int)0x9300),
	AtomicCounterBufferIndex =  unchecked((int)0x9301),
	BufferBinding =  unchecked((int)0x9302),
	BufferDataSize =  unchecked((int)0x9303),
	NumActiveVariables =  unchecked((int)0x9304),
	ActiveVariables =  unchecked((int)0x9305),
	ReferencedByVertexShader =  unchecked((int)0x9306),
	ReferencedByTessControlShader =  unchecked((int)0x9307),
	ReferencedByTessEvaluationShader =  unchecked((int)0x9308),
	ReferencedByGeometryShader =  unchecked((int)0x9309),
	ReferencedByFragmentShader =  unchecked((int)0x930A),
	ReferencedByComputeShader =  unchecked((int)0x930B),
	TopLevelArraySize =  unchecked((int)0x930C),
	TopLevelArrayStride =  unchecked((int)0x930D),
	Location =  unchecked((int)0x930E),
	LocationIndex =  unchecked((int)0x930F),
	LocationComponent =  unchecked((int)0x934A),
	TransformFeedbackBufferIndex =  unchecked((int)0x934B),
	TransformFeedbackBufferStride =  unchecked((int)0x934C),
}

#pragma warning restore

