/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ProgramInterfacePName
{
	ActiveResources =  unchecked((int)0x92F5),
	MaxNameLength =  unchecked((int)0x92F6),
	MaxNumActiveVariables =  unchecked((int)0x92F7),
	MaxNumCompatibleSubroutines =  unchecked((int)0x92F8),
}

#pragma warning restore

