/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum QueryObjectParameterName
{
	QueryTarget =  unchecked((int)0x82EA),
	QueryResult =  unchecked((int)0x8866),
	QueryResultAvailable =  unchecked((int)0x8867),
	QueryResultNoWait =  unchecked((int)0x9194),
}

#pragma warning restore

