/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum QueryTarget
{
	TransformFeedbackOverflow =  unchecked((int)0x82EC),
	VerticesSubmitted =  unchecked((int)0x82EE),
	PrimitivesSubmitted =  unchecked((int)0x82EF),
	VertexShaderInvocations =  unchecked((int)0x82F0),
	TimeElapsed =  unchecked((int)0x88BF),
	SamplesPassed =  unchecked((int)0x8914),
	AnySamplesPassed =  unchecked((int)0x8C2F),
	PrimitivesGenerated =  unchecked((int)0x8C87),
	TransformFeedbackPrimitivesWritten =  unchecked((int)0x8C88),
	AnySamplesPassedConservative =  unchecked((int)0x8D6A),
}

#pragma warning restore

