/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum RenderbufferParameterName
{
	RenderbufferCoverageSamplesNv =  unchecked((int)0x8CAB),
	RenderbufferSamples =  unchecked((int)0x8CAB),
	RenderbufferSamplesAngle =  unchecked((int)0x8CAB),
	RenderbufferSamplesApple =  unchecked((int)0x8CAB),
	RenderbufferSamplesExt =  unchecked((int)0x8CAB),
	RenderbufferSamplesNv =  unchecked((int)0x8CAB),
	RenderbufferWidth =  unchecked((int)0x8D42),
	RenderbufferWidthExt =  unchecked((int)0x8D42),
	RenderbufferWidthOes =  unchecked((int)0x8D42),
	RenderbufferHeight =  unchecked((int)0x8D43),
	RenderbufferHeightExt =  unchecked((int)0x8D43),
	RenderbufferHeightOes =  unchecked((int)0x8D43),
	RenderbufferInternalFormat =  unchecked((int)0x8D44),
	RenderbufferInternalFormatExt =  unchecked((int)0x8D44),
	RenderbufferInternalFormatOes =  unchecked((int)0x8D44),
	RenderbufferRedSize =  unchecked((int)0x8D50),
	RenderbufferRedSizeExt =  unchecked((int)0x8D50),
	RenderbufferRedSizeOes =  unchecked((int)0x8D50),
	RenderbufferGreenSize =  unchecked((int)0x8D51),
	RenderbufferGreenSizeExt =  unchecked((int)0x8D51),
	RenderbufferGreenSizeOes =  unchecked((int)0x8D51),
	RenderbufferBlueSize =  unchecked((int)0x8D52),
	RenderbufferBlueSizeExt =  unchecked((int)0x8D52),
	RenderbufferBlueSizeOes =  unchecked((int)0x8D52),
	RenderbufferAlphaSize =  unchecked((int)0x8D53),
	RenderbufferAlphaSizeExt =  unchecked((int)0x8D53),
	RenderbufferAlphaSizeOes =  unchecked((int)0x8D53),
	RenderbufferDepthSize =  unchecked((int)0x8D54),
	RenderbufferDepthSizeExt =  unchecked((int)0x8D54),
	RenderbufferDepthSizeOes =  unchecked((int)0x8D54),
	RenderbufferStencilSize =  unchecked((int)0x8D55),
	RenderbufferStencilSizeExt =  unchecked((int)0x8D55),
	RenderbufferStencilSizeOes =  unchecked((int)0x8D55),
	RenderbufferColorSamplesNv =  unchecked((int)0x8E10),
	RenderbufferSamplesImg =  unchecked((int)0x9133),
	RenderbufferStorageSamplesAmd =  unchecked((int)0x91B2),
}

#pragma warning restore

