/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum RenderbufferTarget
{
	Renderbuffer =  unchecked((int)0x8D41),
	RenderbufferOes =  unchecked((int)0x8D41),
}

#pragma warning restore

