/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SamplePatternEXT
{
	_1passExt =  unchecked((int)0x80A1),
	_2pass0Ext =  unchecked((int)0x80A2),
	_2pass1Ext =  unchecked((int)0x80A3),
	_4pass0Ext =  unchecked((int)0x80A4),
	_4pass1Ext =  unchecked((int)0x80A5),
	_4pass2Ext =  unchecked((int)0x80A6),
	_4pass3Ext =  unchecked((int)0x80A7),
}

#pragma warning restore

