/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SamplerParameterI
{
	TextureMagFilter =  unchecked((int)0x2800),
	TextureMinFilter =  unchecked((int)0x2801),
	TextureWrapS =  unchecked((int)0x2802),
	TextureWrapT =  unchecked((int)0x2803),
	TextureWrapR =  unchecked((int)0x8072),
	TextureCompareMode =  unchecked((int)0x884C),
	TextureCompareFunc =  unchecked((int)0x884D),
	TextureUnnormalizedCoordinatesArm =  unchecked((int)0x8F6A),
}

#pragma warning restore

