/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SamplePatternEXT
{
	1passExt =  unchecked((int)0x80A1),
	2pass0Ext =  unchecked((int)0x80A2),
	2pass1Ext =  unchecked((int)0x80A3),
	4pass0Ext =  unchecked((int)0x80A4),
	4pass1Ext =  unchecked((int)0x80A5),
	4pass2Ext =  unchecked((int)0x80A6),
	4pass3Ext =  unchecked((int)0x80A7),
}

#pragma warning restore

