/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SamplerParameterF
{
	TextureBorderColor =  unchecked((int)0x1004),
	TextureMinLod =  unchecked((int)0x813A),
	TextureMaxLod =  unchecked((int)0x813B),
	TextureMaxAnisotropy =  unchecked((int)0x84FE),
	TextureLodBias =  unchecked((int)0x8501),
	TextureUnnormalizedCoordinatesArm =  unchecked((int)0x8F6A),
}

#pragma warning restore

