/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SemaphoreParameterName
{
	D3d12FenceValueExt =  unchecked((int)0x9595),
	TimelineSemaphoreValueNv =  unchecked((int)0x9595),
	SemaphoreTypeNv =  unchecked((int)0x95B3),
	SemaphoreTypeBinaryNv =  unchecked((int)0x95B4),
	SemaphoreTypeTimelineNv =  unchecked((int)0x95B5),
}

#pragma warning restore

