/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SeparableTargetEXT
{
	Separable2d =  unchecked((int)0x8012),
	Separable2dExt =  unchecked((int)0x8012),
}

#pragma warning restore

