/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ShadingRate
{
	ShadingRate1x1PixelsExt =  unchecked((int)0x96A6),
	ShadingRate1x2PixelsExt =  unchecked((int)0x96A7),
	ShadingRate2x1PixelsExt =  unchecked((int)0x96A8),
	ShadingRate2x2PixelsExt =  unchecked((int)0x96A9),
	ShadingRate1x4PixelsExt =  unchecked((int)0x96AA),
	ShadingRate4x1PixelsExt =  unchecked((int)0x96AB),
	ShadingRate4x2PixelsExt =  unchecked((int)0x96AC),
	ShadingRate2x4PixelsExt =  unchecked((int)0x96AD),
	ShadingRate4x4PixelsExt =  unchecked((int)0x96AE),
}

#pragma warning restore

