/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ShaderType
{
	FragmentShader =  unchecked((int)0x8B30),
	FragmentShaderArb =  unchecked((int)0x8B30),
	VertexShader =  unchecked((int)0x8B31),
	VertexShaderArb =  unchecked((int)0x8B31),
	GeometryShader =  unchecked((int)0x8DD9),
	TessEvaluationShader =  unchecked((int)0x8E87),
	TessControlShader =  unchecked((int)0x8E88),
	ComputeShader =  unchecked((int)0x91B9),
}

#pragma warning restore

