/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ShadingRateQCOM
{
	ShadingRate1x1PixelsQcom =  unchecked((int)0x96A6),
	ShadingRate1x2PixelsQcom =  unchecked((int)0x96A7),
	ShadingRate2x1PixelsQcom =  unchecked((int)0x96A8),
	ShadingRate2x2PixelsQcom =  unchecked((int)0x96A9),
	ShadingRate1x4PixelsQcom =  unchecked((int)0x96AA),
	ShadingRate4x1PixelsQcom =  unchecked((int)0x96AB),
	ShadingRate4x2PixelsQcom =  unchecked((int)0x96AC),
	ShadingRate2x4PixelsQcom =  unchecked((int)0x96AD),
	ShadingRate4x4PixelsQcom =  unchecked((int)0x96AE),
}

#pragma warning restore

