/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ShaderParameterName
{
	ShaderType =  unchecked((int)0x8B4F),
	DeleteStatus =  unchecked((int)0x8B80),
	CompileStatus =  unchecked((int)0x8B81),
	InfoLogLength =  unchecked((int)0x8B84),
	ShaderSourceLength =  unchecked((int)0x8B88),
}

#pragma warning restore

