/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum ShaderBinaryFormat
{
	SgxBinaryImg =  unchecked((int)0x8C0A),
	MaliShaderBinaryArm =  unchecked((int)0x8F60),
	ShaderBinaryViv =  unchecked((int)0x8FC4),
	ShaderBinaryDmp =  unchecked((int)0x9250),
	GccsoShaderBinaryFj =  unchecked((int)0x9260),
	ShaderBinaryFormatSpirV =  unchecked((int)0x9551),
}

#pragma warning restore

