/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SpecialNumbers
{
	False =  unchecked((int)0),
	NoError =  unchecked((int)0),
	Zero =  unchecked((int)0),
	None =  unchecked((int)0),
	NoneOes =  unchecked((int)0),
	True =  unchecked((int)1),
	One =  unchecked((int)1),
	InvalidIndex =  unchecked((int)0xFFFFFFFF),
	AllPixelsAmd =  unchecked((int)0xFFFFFFFF),
	TimeoutIgnored =  unchecked((int)0xFFFFFFFFFFFFFFFF),
	TimeoutIgnoredApple =  unchecked((int)0xFFFFFFFFFFFFFFFF),
	VersionEsCl10 =  unchecked((int)1),
	VersionEsCm11 =  unchecked((int)1),
	VersionEsCl11 =  unchecked((int)1),
	UuidSizeExt =  unchecked((int)16),
	LuidSizeExt =  unchecked((int)8),
}

#pragma warning restore

