/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SpriteModeSGIX
{
	SpriteAxialSgix =  unchecked((int)0x814C),
	SpriteObjectAlignedSgix =  unchecked((int)0x814D),
	SpriteEyeAlignedSgix =  unchecked((int)0x814E),
}

#pragma warning restore

