/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum StencilOp
{
	Zero =  unchecked((int)0),
	Invert =  unchecked((int)0x150A),
	Keep =  unchecked((int)0x1E00),
	Replace =  unchecked((int)0x1E01),
	Incr =  unchecked((int)0x1E02),
	Decr =  unchecked((int)0x1E03),
	IncrWrap =  unchecked((int)0x8507),
	DecrWrap =  unchecked((int)0x8508),
}

#pragma warning restore

