/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum StringName
{
	Vendor =  unchecked((int)0x1F00),
	Renderer =  unchecked((int)0x1F01),
	Version =  unchecked((int)0x1F02),
	Extensions =  unchecked((int)0x1F03),
	ShadingLanguageVersion =  unchecked((int)0x8B8C),
}

#pragma warning restore

