/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SubgroupSupportedFeatures
{
	SubgroupFeatureBasicBitKhr =  unchecked((int)0x00000001),
	SubgroupFeatureVoteBitKhr =  unchecked((int)0x00000002),
	SubgroupFeatureArithmeticBitKhr =  unchecked((int)0x00000004),
	SubgroupFeatureBallotBitKhr =  unchecked((int)0x00000008),
	SubgroupFeatureShuffleBitKhr =  unchecked((int)0x00000010),
	SubgroupFeatureShuffleRelativeBitKhr =  unchecked((int)0x00000020),
	SubgroupFeatureClusteredBitKhr =  unchecked((int)0x00000040),
	SubgroupFeatureQuadBitKhr =  unchecked((int)0x00000080),
	SubgroupFeaturePartitionedBitNv =  unchecked((int)0x00000100),
}

#pragma warning restore

