/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SubroutineParameterName
{
	UniformSize =  unchecked((int)0x8A38),
	UniformNameLength =  unchecked((int)0x8A39),
	NumCompatibleSubroutines =  unchecked((int)0x8E4A),
	CompatibleSubroutines =  unchecked((int)0x8E4B),
}

#pragma warning restore

