/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SwizzleOpATI
{
	SwizzleStrAti =  unchecked((int)0x8976),
	SwizzleStqAti =  unchecked((int)0x8977),
	SwizzleStrDrAti =  unchecked((int)0x8978),
	SwizzleStqDqAti =  unchecked((int)0x8979),
}

#pragma warning restore

