/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SyncObjectMask
{
	SyncFlushCommandsBit =  unchecked((int)0x00000001),
	SyncFlushCommandsBitApple =  unchecked((int)0x00000001),
}

#pragma warning restore

