/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SyncCondition
{
	SyncGpuCommandsComplete =  unchecked((int)0x9117),
}

#pragma warning restore

