/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum SyncParameterName
{
	ObjectType =  unchecked((int)0x9112),
	SyncCondition =  unchecked((int)0x9113),
	SyncStatus =  unchecked((int)0x9114),
	SyncFlags =  unchecked((int)0x9115),
}

#pragma warning restore

