/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TexStorageAttribs
{
	SurfaceCompressionExt =  unchecked((int)0x96C0),
	SurfaceCompressionFixedRateNoneExt =  unchecked((int)0x96C1),
	SurfaceCompressionFixedRateDefaultExt =  unchecked((int)0x96C2),
	SurfaceCompressionFixedRate1bpcExt =  unchecked((int)0x96C4),
	SurfaceCompressionFixedRate2bpcExt =  unchecked((int)0x96C5),
	SurfaceCompressionFixedRate3bpcExt =  unchecked((int)0x96C6),
	SurfaceCompressionFixedRate4bpcExt =  unchecked((int)0x96C7),
	SurfaceCompressionFixedRate5bpcExt =  unchecked((int)0x96C8),
	SurfaceCompressionFixedRate6bpcExt =  unchecked((int)0x96C9),
	SurfaceCompressionFixedRate7bpcExt =  unchecked((int)0x96CA),
	SurfaceCompressionFixedRate8bpcExt =  unchecked((int)0x96CB),
	SurfaceCompressionFixedRate9bpcExt =  unchecked((int)0x96CC),
	SurfaceCompressionFixedRate10bpcExt =  unchecked((int)0x96CD),
	SurfaceCompressionFixedRate11bpcExt =  unchecked((int)0x96CE),
	SurfaceCompressionFixedRate12bpcExt =  unchecked((int)0x96CF),
}

#pragma warning restore

