/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TextureEnvMode
{
	Add =  unchecked((int)0x0104),
	Blend =  unchecked((int)0x0BE2),
	Replace =  unchecked((int)0x1E01),
	Modulate =  unchecked((int)0x2100),
	Decal =  unchecked((int)0x2101),
	ReplaceExt =  unchecked((int)0x8062),
	TextureEnvBiasSgix =  unchecked((int)0x80BE),
	Combine =  unchecked((int)0x8570),
}

#pragma warning restore

