/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TextureLayout
{
	LayoutDepthReadOnlyStencilAttachmentExt =  unchecked((int)0x9530),
	LayoutDepthAttachmentStencilReadOnlyExt =  unchecked((int)0x9531),
	LayoutGeneralExt =  unchecked((int)0x958D),
	LayoutColorAttachmentExt =  unchecked((int)0x958E),
	LayoutDepthStencilAttachmentExt =  unchecked((int)0x958F),
	LayoutDepthStencilReadOnlyExt =  unchecked((int)0x9590),
	LayoutShaderReadOnlyExt =  unchecked((int)0x9591),
	LayoutTransferSrcExt =  unchecked((int)0x9592),
	LayoutTransferDstExt =  unchecked((int)0x9593),
}

#pragma warning restore

