/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TextureCompareMode
{
	None =  unchecked((int)0),
	CompareRToTexture =  unchecked((int)0x884E),
	CompareRefToTexture =  unchecked((int)0x884E),
}

#pragma warning restore

