/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TextureMinFilter
{
	Nearest =  unchecked((int)0x2600),
	Linear =  unchecked((int)0x2601),
	NearestMipmapNearest =  unchecked((int)0x2700),
	LinearMipmapNearest =  unchecked((int)0x2701),
	NearestMipmapLinear =  unchecked((int)0x2702),
	LinearMipmapLinear =  unchecked((int)0x2703),
	Filter4Sgis =  unchecked((int)0x8146),
	LinearClipmapLinearSgix =  unchecked((int)0x8170),
	PixelTexGenQCeilingSgix =  unchecked((int)0x8184),
	PixelTexGenQRoundSgix =  unchecked((int)0x8185),
	PixelTexGenQFloorSgix =  unchecked((int)0x8186),
	NearestClipmapNearestSgix =  unchecked((int)0x844D),
	NearestClipmapLinearSgix =  unchecked((int)0x844E),
	LinearClipmapNearestSgix =  unchecked((int)0x844F),
}

#pragma warning restore

