/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TextureGenParameter
{
	TextureGenMode =  unchecked((int)0x2500),
	TextureGenModeOes =  unchecked((int)0x2500),
	ObjectPlane =  unchecked((int)0x2501),
	EyePlane =  unchecked((int)0x2502),
	EyePointSgis =  unchecked((int)0x81F4),
	ObjectPointSgis =  unchecked((int)0x81F5),
	EyeLineSgis =  unchecked((int)0x81F6),
	ObjectLineSgis =  unchecked((int)0x81F7),
}

#pragma warning restore

