/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TextureMagFilter
{
	Nearest =  unchecked((int)0x2600),
	Linear =  unchecked((int)0x2601),
	LinearDetailSgis =  unchecked((int)0x8097),
	LinearDetailAlphaSgis =  unchecked((int)0x8098),
	LinearDetailColorSgis =  unchecked((int)0x8099),
	LinearSharpenSgis =  unchecked((int)0x80AD),
	LinearSharpenAlphaSgis =  unchecked((int)0x80AE),
	LinearSharpenColorSgis =  unchecked((int)0x80AF),
	Filter4Sgis =  unchecked((int)0x8146),
	PixelTexGenQCeilingSgix =  unchecked((int)0x8184),
	PixelTexGenQRoundSgix =  unchecked((int)0x8185),
	PixelTexGenQFloorSgix =  unchecked((int)0x8186),
}

#pragma warning restore

