/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp764D.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TextureUnit
{
	Texture0 =  unchecked((int)0x84C0),
	Texture1 =  unchecked((int)0x84C1),
	Texture2 =  unchecked((int)0x84C2),
	Texture3 =  unchecked((int)0x84C3),
	Texture4 =  unchecked((int)0x84C4),
	Texture5 =  unchecked((int)0x84C5),
	Texture6 =  unchecked((int)0x84C6),
	Texture7 =  unchecked((int)0x84C7),
	Texture8 =  unchecked((int)0x84C8),
	Texture9 =  unchecked((int)0x84C9),
	Texture10 =  unchecked((int)0x84CA),
	Texture11 =  unchecked((int)0x84CB),
	Texture12 =  unchecked((int)0x84CC),
	Texture13 =  unchecked((int)0x84CD),
	Texture14 =  unchecked((int)0x84CE),
	Texture15 =  unchecked((int)0x84CF),
	Texture16 =  unchecked((int)0x84D0),
	Texture17 =  unchecked((int)0x84D1),
	Texture18 =  unchecked((int)0x84D2),
	Texture19 =  unchecked((int)0x84D3),
	Texture20 =  unchecked((int)0x84D4),
	Texture21 =  unchecked((int)0x84D5),
	Texture22 =  unchecked((int)0x84D6),
	Texture23 =  unchecked((int)0x84D7),
	Texture24 =  unchecked((int)0x84D8),
	Texture25 =  unchecked((int)0x84D9),
	Texture26 =  unchecked((int)0x84DA),
	Texture27 =  unchecked((int)0x84DB),
	Texture28 =  unchecked((int)0x84DC),
	Texture29 =  unchecked((int)0x84DD),
	Texture30 =  unchecked((int)0x84DE),
	Texture31 =  unchecked((int)0x84DF),
}

#pragma warning restore

