/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TextureSwizzle
{
	Zero =  unchecked((int)0),
	One =  unchecked((int)1),
	Red =  unchecked((int)0x1903),
	Green =  unchecked((int)0x1904),
	Blue =  unchecked((int)0x1905),
	Alpha =  unchecked((int)0x1906),
}

#pragma warning restore

