/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TextureGenMode
{
	EyeLinear =  unchecked((int)0x2400),
	ObjectLinear =  unchecked((int)0x2401),
	SphereMap =  unchecked((int)0x2402),
	EyeDistanceToPointSgis =  unchecked((int)0x81F0),
	ObjectDistanceToPointSgis =  unchecked((int)0x81F1),
	EyeDistanceToLineSgis =  unchecked((int)0x81F2),
	ObjectDistanceToLineSgis =  unchecked((int)0x81F3),
}

#pragma warning restore

