/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TextureWrapMode
{
	LinearMipmapLinear =  unchecked((int)0x2703),
	Clamp =  unchecked((int)0x2900),
	Repeat =  unchecked((int)0x2901),
	ClampToBorder =  unchecked((int)0x812D),
	ClampToBorderArb =  unchecked((int)0x812D),
	ClampToBorderNv =  unchecked((int)0x812D),
	ClampToBorderSgis =  unchecked((int)0x812D),
	ClampToEdge =  unchecked((int)0x812F),
	ClampToEdgeSgis =  unchecked((int)0x812F),
	MirroredRepeat =  unchecked((int)0x8370),
}

#pragma warning restore

