/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TextureCoordName
{
	S =  unchecked((int)0x2000),
	T =  unchecked((int)0x2001),
	R =  unchecked((int)0x2002),
	Q =  unchecked((int)0x2003),
	TextureGenStrOes =  unchecked((int)0x8D60),
}

#pragma warning restore

