/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TextureEnvTarget
{
	TextureEnv =  unchecked((int)0x2300),
	TextureFilterControl =  unchecked((int)0x8500),
	PointSprite =  unchecked((int)0x8861),
}

#pragma warning restore

