/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TraceMaskMESA
{
	TraceOperationsBitMesa =  unchecked((int)0x0001),
	TracePrimitivesBitMesa =  unchecked((int)0x0002),
	TraceArraysBitMesa =  unchecked((int)0x0004),
	TraceTexturesBitMesa =  unchecked((int)0x0008),
	TracePixelsBitMesa =  unchecked((int)0x0010),
	TraceErrorsBitMesa =  unchecked((int)0x0020),
	TraceAllBitsMesa =  unchecked((int)0xFFFF),
}

#pragma warning restore

