/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TransformFeedbackPName
{
	TransformFeedbackBufferStart =  unchecked((int)0x8C84),
	TransformFeedbackBufferSize =  unchecked((int)0x8C85),
	TransformFeedbackBufferBinding =  unchecked((int)0x8C8F),
	TransformFeedbackPaused =  unchecked((int)0x8E23),
	TransformFeedbackActive =  unchecked((int)0x8E24),
}

#pragma warning restore

