/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TransformFeedbackTokenNV
{
	NextBufferNv =  unchecked((int)-2),
	SkipComponents4Nv =  unchecked((int)-3),
	SkipComponents3Nv =  unchecked((int)-4),
	SkipComponents2Nv =  unchecked((int)-5),
	SkipComponents1Nv =  unchecked((int)-6),
}

#pragma warning restore

