/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TriangleListSUN
{
	RestartSun =  unchecked((int)0x0001),
	ReplaceMiddleSun =  unchecked((int)0x0002),
	ReplaceOldestSun =  unchecked((int)0x0003),
}

#pragma warning restore

