/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum TriangleFace
{
	Front =  unchecked((int)0x0404),
	Back =  unchecked((int)0x0405),
	FrontAndBack =  unchecked((int)0x0408),
}

#pragma warning restore

