/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum UniformPName
{
	UniformType =  unchecked((int)0x8A37),
	UniformSize =  unchecked((int)0x8A38),
	UniformNameLength =  unchecked((int)0x8A39),
	UniformBlockIndex =  unchecked((int)0x8A3A),
	UniformOffset =  unchecked((int)0x8A3B),
	UniformArrayStride =  unchecked((int)0x8A3C),
	UniformMatrixStride =  unchecked((int)0x8A3D),
	UniformIsRowMajor =  unchecked((int)0x8A3E),
	UniformAtomicCounterBufferIndex =  unchecked((int)0x92DA),
}

#pragma warning restore

