/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Generation time: 11.04.2023 22:26:19
 *  Source files: [C:\!Temp\tmp4252.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum UniformBlockPName
{
	UniformBlockReferencedByTessControlShader =  unchecked((int)0x84F0),
	UniformBlockReferencedByTessEvaluationShader =  unchecked((int)0x84F1),
	UniformBlockBinding =  unchecked((int)0x8A3F),
	UniformBlockDataSize =  unchecked((int)0x8A40),
	UniformBlockNameLength =  unchecked((int)0x8A41),
	UniformBlockActiveUniforms =  unchecked((int)0x8A42),
	UniformBlockActiveUniformIndices =  unchecked((int)0x8A43),
	UniformBlockReferencedByVertexShader =  unchecked((int)0x8A44),
	UniformBlockReferencedByGeometryShader =  unchecked((int)0x8A45),
	UniformBlockReferencedByFragmentShader =  unchecked((int)0x8A46),
	UniformBlockReferencedByComputeShader =  unchecked((int)0x90EC),
}

#pragma warning restore

