/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum UseProgramStageMask
{
	VertexShaderBit =  unchecked((int)0x00000001),
	VertexShaderBitExt =  unchecked((int)0x00000001),
	FragmentShaderBit =  unchecked((int)0x00000002),
	FragmentShaderBitExt =  unchecked((int)0x00000002),
	GeometryShaderBit =  unchecked((int)0x00000004),
	GeometryShaderBitExt =  unchecked((int)0x00000004),
	GeometryShaderBitOes =  unchecked((int)0x00000004),
	TessControlShaderBit =  unchecked((int)0x00000008),
	TessControlShaderBitExt =  unchecked((int)0x00000008),
	TessControlShaderBitOes =  unchecked((int)0x00000008),
	TessEvaluationShaderBit =  unchecked((int)0x00000010),
	TessEvaluationShaderBitExt =  unchecked((int)0x00000010),
	TessEvaluationShaderBitOes =  unchecked((int)0x00000010),
	ComputeShaderBit =  unchecked((int)0x00000020),
	MeshShaderBitNv =  unchecked((int)0x00000040),
	TaskShaderBitNv =  unchecked((int)0x00000080),
	AllShaderBits =  unchecked((int)0xFFFFFFFF),
	AllShaderBitsExt =  unchecked((int)0xFFFFFFFF),
}

#pragma warning restore

