/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum VertexProvokingMode
{
	FirstVertexConvention =  unchecked((int)0x8E4D),
	LastVertexConvention =  unchecked((int)0x8E4E),
}

#pragma warning restore

