/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum VertexStreamATI
{
	VertexStream0Ati =  unchecked((int)0x876C),
	VertexStream1Ati =  unchecked((int)0x876D),
	VertexStream2Ati =  unchecked((int)0x876E),
	VertexStream3Ati =  unchecked((int)0x876F),
	VertexStream4Ati =  unchecked((int)0x8770),
	VertexStream5Ati =  unchecked((int)0x8771),
	VertexStream6Ati =  unchecked((int)0x8772),
	VertexStream7Ati =  unchecked((int)0x8773),
}

#pragma warning restore

