/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum VertexAttribEnum
{
	VertexAttribArrayEnabled =  unchecked((int)0x8622),
	VertexAttribArraySize =  unchecked((int)0x8623),
	VertexAttribArrayStride =  unchecked((int)0x8624),
	VertexAttribArrayType =  unchecked((int)0x8625),
	CurrentVertexAttrib =  unchecked((int)0x8626),
	VertexAttribArrayNormalized =  unchecked((int)0x886A),
	VertexAttribArrayBufferBinding =  unchecked((int)0x889F),
	VertexAttribArrayInteger =  unchecked((int)0x88FD),
	VertexAttribArrayDivisor =  unchecked((int)0x88FE),
}

#pragma warning restore

