/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum VertexAttribPointerPropertyARB
{
	VertexAttribArrayPointer =  unchecked((int)0x8645),
	VertexAttribArrayPointerArb =  unchecked((int)0x8645),
}

#pragma warning restore

