/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum VertexHintsMaskPGI
{
	Vertex23BitPgi =  unchecked((int)0x00000004),
	Vertex4BitPgi =  unchecked((int)0x00000008),
	Color3BitPgi =  unchecked((int)0x00010000),
	Color4BitPgi =  unchecked((int)0x00020000),
	EdgeflagBitPgi =  unchecked((int)0x00040000),
	IndexBitPgi =  unchecked((int)0x00080000),
	MatAmbientBitPgi =  unchecked((int)0x00100000),
	MatAmbientAndDiffuseBitPgi =  unchecked((int)0x00200000),
	MatDiffuseBitPgi =  unchecked((int)0x00400000),
	MatEmissionBitPgi =  unchecked((int)0x00800000),
	MatColorIndexesBitPgi =  unchecked((int)0x01000000),
	MatShininessBitPgi =  unchecked((int)0x02000000),
	MatSpecularBitPgi =  unchecked((int)0x04000000),
	NormalBitPgi =  unchecked((int)0x08000000),
	Texcoord1BitPgi =  unchecked((int)0x10000000),
	Texcoord2BitPgi =  unchecked((int)0x20000000),
	Texcoord3BitPgi =  unchecked((int)0x40000000),
	Texcoord4BitPgi =  unchecked((int)0x80000000),
}

#pragma warning restore

