/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum VertexShaderTextureUnitParameter
{
	CurrentTextureCoords =  unchecked((int)0x0B03),
	TextureMatrix =  unchecked((int)0x0BA8),
}

#pragma warning restore

