/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp97CC.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum VertexAttribIType
{
	Byte =  unchecked((int)0x1400),
	UnsignedByte =  unchecked((int)0x1401),
	Short =  unchecked((int)0x1402),
	UnsignedShort =  unchecked((int)0x1403),
	Int =  unchecked((int)0x1404),
	UnsignedInt =  unchecked((int)0x1405),
}

#pragma warning restore

