/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum VertexShaderOpEXT
{
	OpIndexExt =  unchecked((int)0x8782),
	OpNegateExt =  unchecked((int)0x8783),
	OpDot3Ext =  unchecked((int)0x8784),
	OpDot4Ext =  unchecked((int)0x8785),
	OpMulExt =  unchecked((int)0x8786),
	OpAddExt =  unchecked((int)0x8787),
	OpMaddExt =  unchecked((int)0x8788),
	OpFracExt =  unchecked((int)0x8789),
	OpMaxExt =  unchecked((int)0x878A),
	OpMinExt =  unchecked((int)0x878B),
	OpSetGeExt =  unchecked((int)0x878C),
	OpSetLtExt =  unchecked((int)0x878D),
	OpClampExt =  unchecked((int)0x878E),
	OpFloorExt =  unchecked((int)0x878F),
	OpRoundExt =  unchecked((int)0x8790),
	OpExpBase2Ext =  unchecked((int)0x8791),
	OpLogBase2Ext =  unchecked((int)0x8792),
	OpPowerExt =  unchecked((int)0x8793),
	OpRecipExt =  unchecked((int)0x8794),
	OpRecipSqrtExt =  unchecked((int)0x8795),
	OpSubExt =  unchecked((int)0x8796),
	OpCrossProductExt =  unchecked((int)0x8797),
	OpMultiplyMatrixExt =  unchecked((int)0x8798),
	OpMovExt =  unchecked((int)0x8799),
}

#pragma warning restore

