/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum VertexShaderStorageTypeEXT
{
	VariantExt =  unchecked((int)0x87C1),
	InvariantExt =  unchecked((int)0x87C2),
	LocalConstantExt =  unchecked((int)0x87C3),
	LocalExt =  unchecked((int)0x87C4),
}

#pragma warning restore

