/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmp3921.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum VertexAttribType
{
	Byte =  unchecked((int)0x1400),
	UnsignedByte =  unchecked((int)0x1401),
	Short =  unchecked((int)0x1402),
	UnsignedShort =  unchecked((int)0x1403),
	Int =  unchecked((int)0x1404),
	UnsignedInt =  unchecked((int)0x1405),
	Float =  unchecked((int)0x1406),
	Double =  unchecked((int)0x140A),
	HalfFloat =  unchecked((int)0x140B),
	Fixed =  unchecked((int)0x140C),
	UnsignedInt2101010Rev =  unchecked((int)0x8368),
	UnsignedInt2101010RevExt =  unchecked((int)0x8368),
	UnsignedInt10f11f11fRev =  unchecked((int)0x8C3B),
	Int2101010Rev =  unchecked((int)0x8D9F),
}

#pragma warning restore

