/*  This file is automatic generated by NiTiS-Dev/NiTiS.Native:CodeGen
 *  Source files: [C:\!Temp\tmpFE2.tmp]
 */
#pragma warning disable 1591

namespace NiTiS.Native.OpenGL.Enums;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public enum VertexShaderCoordOutEXT
{
	XExt =  unchecked((int)0x87D5),
	YExt =  unchecked((int)0x87D6),
	ZExt =  unchecked((int)0x87D7),
	WExt =  unchecked((int)0x87D8),
	NegativeXExt =  unchecked((int)0x87D9),
	NegativeYExt =  unchecked((int)0x87DA),
	NegativeZExt =  unchecked((int)0x87DB),
	NegativeWExt =  unchecked((int)0x87DC),
	ZeroExt =  unchecked((int)0x87DD),
	OneExt =  unchecked((int)0x87DE),
	NegativeOneExt =  unchecked((int)0x87DF),
}

#pragma warning restore

