name: GLFW
on:
  workflow_dispatch:

  push:
    branches-ignore:
      - "ci/*"
      - "feature/*"
      - "dev"
    paths:
      - "build/submodules/GLFW"
      - "build/Build+Native+GLFW.cs"

jobs:
  glfw-build:
    strategy: 
      fail-fast: false
      matrix:
        env:
          - os: ubuntu-latest
            name: Linux
            nuke_invoke: ./build.sh glfw
            extras: |
              sudo apt-get update
              sudo apt-get install -y xorg-dev 
          - os: windows-latest
            name: Windows
            nuke_invoke: ./build.cmd glfw
            extras: ""
          - os: macos-latest
            name: Darwin
            nuke_invoke: ./build.sh glfw
            extras: ""
          
    name: ${{ matrix.env.name }} Glfw Build
    runs-on: ${{ matrix.env.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout submodules, configure git
        run: |
          git -c submodule.third_party/git-hooks.update=none submodule update --init --recursive
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "actions" 
      - name: Extra prerequisites
        run: |
          echo running extras
          ${{ matrix.env.extras }}
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.201
      - name: Build GLFW
        run: ${{ matrix.env.nuke_invoke }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

