name: NuGet & Github Push

on:
  push:
    branches-ignore:
      - "ci/*"
      - "feature/*"
      - "dev"
    paths:
    - '**.cs'
    - '**.csproj'
    - '.github/workflows/test.yml'
  
  workflow_dispatch:
  
jobs:
  push:
    name: NuGet Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules, configure git
        run: |
          git -c submodule.third_party/git-hooks.update=none submodule update --init --recursive
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "actions" 

      - name: Push
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./build.sh PushToAll
      
      #- name: Nuget Upload
      #  if: (github.event_name == 'push')
      #  run: |
      #    cd .pack/
      #    dotnet nuget push ${{ matrix.project }}/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN} --skip-duplicate
      #  env:
      #    NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}   
      
      #- name: Github Upload
      #  if: (github.event_name == 'push')
      #  run: |
      #    cd .pack/
      #    dotnet nuget push ${{ matrix.project }}/*.nupkg --source https://nuget.pkg.github.com/NiTiS-Dev/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
