name: Test Build

on:
  push:
    branches-ignore:
      - "ci/*"
      - "feature/*"
      - "dev"
    paths:
    - '**.cs'
    - '**.csproj'
    - '.github/workflows/test.yml'

  pull_request:
  
  workflow_dispatch:
  
jobs:
  test:
    strategy: 
      fail-fast: false
      matrix:
        env:
          - os: ubuntu-latest
            name: Linux
            nuke_invoke: ./build.sh Compile
          - os: windows-latest
            name: Windows
            nuke_invoke: ./build.cmd Compile
          - os: macos-latest
            name: Darwin
            nuke_invoke: ./build.sh Compile
    
    name: ${{ matrix.env.name }} Test
    runs-on: ${{ matrix.env.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules, configure git
        run: |
          git -c submodule.third_party/git-hooks.update=none submodule update --init --recursive
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "actions" 

      - name: Build
        run: |
          ${{ matrix.env.nuke_invoke }}
          
      - name: Artifact Pack
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts ${{ matrix.env.name }}
          path: output/compile/**/NiTiS.*.dll